# Generated by Django 3.1.8 on 2021-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="category",
            field=models.CharField(
                choices=[
                    ("msrun_protocol", "LC-MS Run Protocol"),
                    ("animal_treatment", "Animal Treatment"),
                ],
                help_text="Classification of the protocol, e.g. an animal treatment or MSRun procedure.",
                max_length=256,
            ),
        ),
    ]
