# Generated by Django 3.1.6 on 2021-03-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="hmdb_id",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
