# Generated by Django 3.1.8 on 2021-05-25 16:02

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0001_reinitialize"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="time_collected",
            field=models.DurationField(
                blank=True,
                help_text=(
                    "The time, in minutes relative to an infusion "
                    "timepoint, that a sample was extracted from a animal"
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(days=-1)
                    ),
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(days=7)
                    ),
                ],
            ),
        ),
    ]
