# Generated by Django 3.2.13 on 2022-06-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infusate',
            name='tracer_group_name',
            field=models.CharField(blank=True, help_text="A short name or lab identifier of refering to a group of tracer compounds, e.g '6eaas'.  There may be multiple infusate records with this group name, each referring to the same tracers at different concentrations.", max_length=20, null=True),
        ),
    ]
