# Generated by Django 3.2.5 on 2022-07-22 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracer',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tracers', to='DataRepo.compound'),
        ),
    ]
