# Generated by Django 3.1.8 on 2021-06-08 19:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.FloatField(
                blank=True,
                help_text="Age of the animal at the time samples were collected (units of weeks).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="diet",
            field=models.CharField(
                blank=True,
                help_text="Feeding descriptor for the animal [e.g. LabDiet Rodent 5001].",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="feeding_status",
            field=models.CharField(
                blank=True,
                help_text="The laboratory coded dietary state for the animal (i.e. fasted).",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(
                help_text="Unique name or lab identifier of a source animal for a series of studied samples.",
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("F", "female"), ("M", "male")],
                help_text="Sex of the animal (i.e. M, F).",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="Researcher code for the state of the studied animal [e.g. fasted].",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="studies",
            field=models.ManyToManyField(
                help_text="Reference(s) to the many possible experimental studies an animal is associated with.",
                related_name="animals",
                to="DataRepo.Study",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="tracer_compound",
            field=models.ForeignKey(
                help_text="Identifier for the Compound which was used as the Tracer.  The tracer (aka infusate) is the labeled compound that is infused into the animal.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="DataRepo.compound",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="tracer_infusion_concentration",
            field=models.FloatField(
                blank=True,
                help_text="Millimolar concentration of the tracer in the solution that was infused (units of mM).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="tracer_infusion_rate",
            field=models.FloatField(
                blank=True,
                help_text="Rate of tracer infusion as microliters/min/gram body weight of the mouse (units of ul/min/g).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="tracer_labeled_atom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Carbon"),
                    ("N", "Nitrogen"),
                    ("H", "Hydrogen"),
                    ("O", "Oxygen"),
                    ("S", "Sulfur"),
                ],
                default="C",
                help_text="The type of atom that is labeled in the tracer compound (i.e. C, H, O).",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="compound",
            name="formula",
            field=models.CharField(
                help_text="molecular formula of the compound [e.g. C6H12O6].",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="compound",
            name="hmdb_id",
            field=models.CharField(
                help_text="unique identifier for this compound in the Human Metabolome Database, https://hmdb.ca/ .",
                max_length=11,
                unique=True,
                verbose_name="HMDB ID",
            ),
        ),
        migrations.AlterField(
            model_name="compound",
            name="name",
            field=models.CharField(
                help_text="Common name of the compound in the laboratory [e.g. glucose].",
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="msrun",
            name="date",
            field=models.DateField(
                help_text="Date the mass spectrometer run was performed."
            ),
        ),
        migrations.AlterField(
            model_name="msrun",
            name="protocol",
            field=models.ForeignKey(
                help_text="Protocol performed for the mass spectrometer run.",
                limit_choices_to={"category": "msrun_protocol"},
                on_delete=django.db.models.deletion.RESTRICT,
                to="DataRepo.protocol",
            ),
        ),
        migrations.AlterField(
            model_name="msrun",
            name="researcher",
            field=models.CharField(
                help_text="Name of the researcher who executed the mass spectrometer run.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="msrun",
            name="sample",
            field=models.ForeignKey(
                help_text="Reference to the sample run on the mass spectrometer.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="msruns",
                to="DataRepo.sample",
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="corrected_abundance",
            field=models.FloatField(
                help_text="Ion counts corrected for natural abundance of isotopomers.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="labeled_element",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Carbon"),
                    ("N", "Nitrogen"),
                    ("H", "Hydrogen"),
                    ("O", "Oxygen"),
                    ("S", "Sulfur"),
                ],
                default="C",
                help_text="The type of element that is labeled in this observation (e.g. C, H, O).",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="med_mz",
            field=models.FloatField(
                help_text="Median mass/charge value of this measurement.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="med_rt",
            field=models.FloatField(
                help_text="Median retention time value of this measurement.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="raw_abundance",
            field=models.FloatField(
                help_text="Ion counts or raw abundance of this observation.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="compounds",
            field=models.ManyToManyField(
                help_text="Database identifier(s) for the TraceBase compound(s) that this PeakGroup describes.",
                related_name="peak_groups",
                to="DataRepo.Compound",
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="formula",
            field=models.CharField(
                help_text="Molecular formula of the compound [e.g. C6H12O6].",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="ms_run",
            field=models.ForeignKey(
                help_text="Database identifier of the MS run this PeakGroup was derived from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
                to="DataRepo.msrun",
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="name",
            field=models.CharField(
                help_text="Compound or isomer group name [e.g. citrate/isocitrate].",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="peak_group_set",
            field=models.ForeignKey(
                help_text="Source file or dataset this PeakGroup was derived from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
                to="DataRepo.peakgroupset",
            ),
        ),
        migrations.AlterField(
            model_name="peakgroupset",
            name="imported_timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp for when the source datafile was imported.",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="description",
            field=models.TextField(
                blank=True, help_text="Full text of the protocol's methods."
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="name",
            field=models.CharField(
                help_text="Unique name of the protocol.", max_length=256, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="animal",
            field=models.ForeignKey(
                help_text="Source animal the sample was extracted from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="DataRepo.animal",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(
                help_text="Unique name of the biological sample.",
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="researcher",
            field=models.CharField(
                help_text="Name of researcher whom prepared sample.", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="tissue",
            field=models.ForeignKey(
                help_text="Laboratory enumerated title of the tissue the sample was extracted from.",
                on_delete=django.db.models.deletion.RESTRICT,
                to="DataRepo.tissue",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Lengthy description of the collection of one or more series of animals, samples, and their assays, which may include experimental design process.",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="name",
            field=models.CharField(
                help_text="Succinct name of the collection of one or more series of animals, samples, and their assays.",
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tissue",
            name="name",
            field=models.CharField(
                help_text="Unique name of the tissue.", max_length=256, unique=True
            ),
        ),
    ]
