# Generated by Django 3.1.8 on 2021-05-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrun",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="msruns",
                to="DataRepo.sample",
            ),
        ),
    ]
