# Generated by Django 3.1.8 on 2021-05-19 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0001_reinitialize"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="time_collected",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The time, in minutes relative to an infusion timepoint, "
                "that a sample was extracted from a animal",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1440),
                    django.core.validators.MaxValueValidator(10080),
                ],
            ),
        ),
    ]
