# Generated by Django 3.1.8 on 2021-05-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0002_sample_time_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                help_text="Lab controlled label of the actions taken on an animal "
                "that are not captured by diet, feeding_status, etc.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="DataRepo.protocol",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="category",
            field=models.CharField(
                choices=[
                    ("msrun_protocol", "LC-MS Run Protocol"),
                    ("animal_treatment", "Animal Treatment"),
                ],
                default="msrun_protocol",
                help_text="Classification of the protocol, referencing it's intended application",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="description",
            field=models.TextField(
                blank=True, help_text="Full text of the protocol's methods"
            ),
        ),
    ]
