# Generated by Django 3.1.8 on 2021-05-21 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0002_sample_time_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="time_collected",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "The time, in minutes relative to an infusion timepoint, "
                    "that a sample was extracted from a animal"
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1440),
                    django.core.validators.MaxValueValidator(10080),
                ],
            ),
        ),
    ]
