# Generated by Django 3.1.6 on 2021-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0002_auto_20210322_1629"),
    ]

    operations = [
        migrations.RenameField(
            model_name="msrun", old_name="protocol_id", new_name="protocol",
        ),
        migrations.RenameField(
            model_name="msrun", old_name="sample_id", new_name="sample",
        ),
        migrations.AlterField(
            model_name="msrun",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
