# Generated by Django 3.2.5 on 2022-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0002_tracer_group_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='peakdatalabel',
            name='unique_peakdata',
        ),
        migrations.AddConstraint(
            model_name='peakdatalabel',
            constraint=models.UniqueConstraint(fields=('peak_data', 'element'), name='unique_peakdata'),
        ),
    ]
