# Generated by Django 3.2.5 on 2022-10-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0002_alter_animal_last_serum_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msrun',
            name='sample',
            field=models.ForeignKey(help_text='The sample that was run on the mass spectrometer.', on_delete=django.db.models.deletion.CASCADE, related_name='msruns', to='DataRepo.sample'),
        ),
    ]
