# Generated by Django 3.1.8 on 2021-05-24 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0002_sample_time_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="time_collected",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text=(
                    "The time, in minutes relative to an infusion "
                    "timepoint, that a sample was extracted from a animal"
                ),
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-1440),
                    django.core.validators.MaxValueValidator(10080),
                ],
            ),
        ),
    ]
