# Generated by Django 3.1.6 on 2021-03-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0003_auto_20210322_1710"),
        ("DataRepo", "0003_study_samples_model"),
    ]

    operations = []
