# Generated by Django 3.2.5 on 2022-08-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0003_auto_20220809_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infusatetracer',
            name='infusate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracer_links', to='DataRepo.infusate'),
        ),
        migrations.AlterField(
            model_name='infusatetracer',
            name='tracer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infusate_links', to='DataRepo.tracer'),
        ),
        migrations.CreateModel(
            name='FCirc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element', models.CharField(choices=[('C', 'Carbon'), ('N', 'Nitrogen'), ('H', 'Hydrogen'), ('O', 'Oxygen'), ('S', 'Sulfur'), ('P', 'Phosphorus')], default='C', help_text='An element that is labeled in any of the tracers in this infusate (e.g. "C", "H", "O").', max_length=1)),
                ('serum_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcircs', to='DataRepo.sample')),
                ('tracer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcircs', to='DataRepo.tracer')),
            ],
            options={
                'verbose_name': 'fcirc',
                'verbose_name_plural': 'fcircs',
                'ordering': ['serum_sample', 'tracer', 'element'],
            },
        ),
        migrations.AddConstraint(
            model_name='fcirc',
            constraint=models.UniqueConstraint(fields=('serum_sample', 'tracer', 'element'), name='unique_fcirc'),
        ),
    ]
