# Generated by Django 3.1.8 on 2021-05-25 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0003_AnimalTreatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                help_text="Lab controlled label of the actions taken on an animal.",
                limit_choices_to={"category": "animal_treatment"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="animals",
                to="DataRepo.protocol",
            ),
        ),
        migrations.AlterField(
            model_name="msrun",
            name="protocol",
            field=models.ForeignKey(
                limit_choices_to={"category": "msrun_protocol"},
                on_delete=django.db.models.deletion.RESTRICT,
                to="DataRepo.protocol",
            ),
        ),
    ]
