# Generated by Django 3.1.8 on 2021-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0003_AnimalTreatment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"verbose_name": "animal", "verbose_name_plural": "animals"},
        ),
        migrations.AlterModelOptions(
            name="compound",
            options={
                "ordering": ["name"],
                "verbose_name": "compound",
                "verbose_name_plural": "compounds",
            },
        ),
        migrations.AlterModelOptions(
            name="msrun",
            options={
                "verbose_name": "mass spectrometry run",
                "verbose_name_plural": "mass spectrometry runs",
            },
        ),
        migrations.AlterModelOptions(
            name="peakdata",
            options={
                "ordering": ["peak_group"],
                "verbose_name": "peak datum",
                "verbose_name_plural": "peak data",
            },
        ),
        migrations.AlterModelOptions(
            name="peakgroup",
            options={
                "verbose_name": "peak group",
                "verbose_name_plural": "peak groups",
            },
        ),
        migrations.AlterModelOptions(
            name="peakgroupset",
            options={
                "verbose_name": "peak group set",
                "verbose_name_plural": "peak group sets",
            },
        ),
        migrations.AlterModelOptions(
            name="protocol",
            options={"verbose_name": "protocol", "verbose_name_plural": "protocols"},
        ),
        migrations.AlterModelOptions(
            name="sample",
            options={
                "ordering": ["name"],
                "verbose_name": "sample",
                "verbose_name_plural": "samples",
            },
        ),
        migrations.AlterModelOptions(
            name="study",
            options={
                "ordering": ["name"],
                "verbose_name": "study",
                "verbose_name_plural": "studies",
            },
        ),
        migrations.AlterModelOptions(
            name="tissue",
            options={"verbose_name": "tissue", "verbose_name_plural": "tissues"},
        ),
        migrations.AlterField(
            model_name="compound",
            name="hmdb_id",
            field=models.CharField(max_length=11, unique=True, verbose_name="HMDB ID"),
        ),
    ]
