# Generated by Django 3.2.4 on 2021-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0003_remove_animal_state"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="peakgroup",
            name="unique_peakgroup",
        ),
        migrations.RenameField(
            model_name="peakgroup",
            old_name="ms_run",
            new_name="msrun",
        ),
        migrations.AddConstraint(
            model_name="peakgroup",
            constraint=models.UniqueConstraint(
                fields=("name", "msrun"), name="unique_peakgroup"
            ),
        ),
    ]
