# Generated by Django 3.2.5 on 2022-08-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0003_auto_20220809_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalTracer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_tracers', to='DataRepo.animal')),
                ('tracer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataRepo.tracer')),
            ],
            options={
                'verbose_name': 'animal_tracer',
                'verbose_name_plural': 'animal_tracers',
                'ordering': ['animal', 'tracer'],
            },
        ),
        migrations.AlterField(
            model_name='infusatetracer',
            name='infusate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracer_links', to='DataRepo.infusate'),
        ),
        migrations.AlterField(
            model_name='infusatetracer',
            name='tracer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infusate_links', to='DataRepo.tracer'),
        ),
        migrations.CreateModel(
            name='AnimalTracerLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element', models.CharField(choices=[('C', 'Carbon'), ('N', 'Nitrogen'), ('H', 'Hydrogen'), ('O', 'Oxygen'), ('S', 'Sulfur'), ('P', 'Phosphorus')], default='C', help_text='An element that is labeled in any of the tracers in this infusate (e.g. "C", "H", "O").', max_length=1)),
                ('animal_tracer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_tracer_labels', to='DataRepo.animaltracer')),
            ],
            options={
                'verbose_name': 'animal_tracer_label',
                'verbose_name_plural': 'animal_tracer_labels',
                'ordering': ['animal_tracer', 'element'],
            },
        ),
        migrations.AddConstraint(
            model_name='animaltracerlabel',
            constraint=models.UniqueConstraint(fields=('animal_tracer', 'element'), name='unique_animal_tracer_label'),
        ),
        migrations.AddConstraint(
            model_name='animaltracer',
            constraint=models.UniqueConstraint(fields=('animal', 'tracer'), name='unique_animal_tracer'),
        ),
    ]
