# Generated by Django 3.2.5 on 2022-10-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0003_alter_msrun_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='infusate',
            field=models.ForeignKey(help_text='The solution infused into the animal containing 1 or more tracer compounds at specific concentrations.', on_delete=django.db.models.deletion.RESTRICT, related_name='animals', to='DataRepo.infusate'),
        ),
    ]
