# Generated by Django 3.2.5 on 2022-08-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0004_auto_20220816_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracer',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracers', to='DataRepo.compound'),
        ),
    ]
