# Generated by Django 3.2.4 on 2021-07-20 18:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0004_StandardizeMsrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DurationField(blank=True, help_text='The age of the animal at the time of samples collection.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='body_weight',
            field=models.FloatField(blank=True, help_text='The weight (in grams) of the animal at the time of sample collection.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='genotype',
            field=models.CharField(help_text='The laboratory standardized genotype of the animal.', max_length=256),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], help_text='The sex of the animal ("male" or "female").', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='peakdata',
            name='raw_abundance',
            field=models.FloatField(help_text='The ion count of this observation.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='The date the sample was collected.'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='time_collected',
            field=models.DurationField(blank=True, help_text='The time, relative to an infusion timepoint, that a sample was extracted from an animal.', null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(days=-1)), django.core.validators.MaxValueValidator(datetime.timedelta(days=7))]),
        ),
    ]
