# Generated by Django 3.1.6 on 2021-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0004_PeakGroup_Data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peakdata",
            name="labeled_element",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Carbon"),
                    ("N", "Nitrogen"),
                    ("H", "Hydrogen"),
                    ("O", "Oxygen"),
                    ("S", "Sulfur"),
                ],
                default="C",
                help_text="the type of element that is labeled in this observation (e.g. C, H, O)",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="formula",
            field=models.CharField(
                help_text="molecular formula of the compound [e.g. C6H12O6]",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="name",
            field=models.CharField(
                help_text="Compound or isomer group name [e.g. citrate/isocitrate]",
                max_length=256,
            ),
        ),
    ]
