# Generated by Django 3.1.8 on 2021-04-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0005_auto_20210421_1054"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msrun",
            name="name",
        ),
        migrations.AddField(
            model_name="msrun",
            name="researcher",
            field=models.CharField(default="default", max_length=256),
            preserve_default=False,
        ),
    ]
