# Generated by Django 3.2.4 on 2021-09-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0005_auto_20210721_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'animal', 'verbose_name_plural': 'animals'},
        ),
        migrations.AlterModelOptions(
            name='msrun',
            options={'ordering': ['date', 'researcher', 'sample__name', 'protocol__name'], 'verbose_name': 'mass spectrometry run', 'verbose_name_plural': 'mass spectrometry runs'},
        ),
        migrations.AlterModelOptions(
            name='peakgroup',
            options={'ordering': ['name'], 'verbose_name': 'peak group', 'verbose_name_plural': 'peak groups'},
        ),
        migrations.AlterModelOptions(
            name='peakgroupset',
            options={'ordering': ['filename'], 'verbose_name': 'peak group set', 'verbose_name_plural': 'peak group sets'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['name'], 'verbose_name': 'protocol', 'verbose_name_plural': 'protocols'},
        ),
        migrations.AlterModelOptions(
            name='tissue',
            options={'ordering': ['name'], 'verbose_name': 'tissue', 'verbose_name_plural': 'tissues'},
        ),
    ]
