# Generated by Django 3.2.5 on 2023-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0005_alter_study_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.TextField(blank=True, help_text="Full text of the protocol's methods.", null=True),
        ),
    ]
