# Generated by Django 3.2.5 on 2022-08-17 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0005_alter_tracer_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='infusate',
            field=models.ForeignKey(blank=True, help_text='The solution infused into the animal containing 1 or more tracer compounds at specific concentrations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='DataRepo.infusate'),
        ),
    ]
