# Generated by Django 3.2.17 on 2023-02-15 20:54

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0006_alter_protocol_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakdatalabel',
            name='count',
            field=models.PositiveSmallIntegerField(help_text='The number of labeled atoms (M+) observed relative to the presumed compound referred to in the peak group.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='peakdatalabel',
            name='mass_number',
            field=models.PositiveSmallIntegerField(help_text="The sum of the number of protons and neutrons of the labeled atom, a.k.a. 'isotope', e.g. Carbon 14.  The number of protons identifies the element that this tracer is an isotope of.  The number of neutrons in the element equals the number of protons, but in an isotope, the number of neutrons will be less than or greater than the number of protons.  Note, this differs from the 'atomic number' which indicates the number of protons only.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tracerlabel',
            name='count',
            field=models.PositiveSmallIntegerField(help_text='The number of labeled atoms (M+) in the tracer compound supplied to this animal.  Note that the count must be greater than or equal to the number of positions.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tracerlabel',
            name='mass_number',
            field=models.PositiveSmallIntegerField(help_text="The sum of the number of protons and neutrons of the labeled atom, a.k.a. 'isotope', e.g. Carbon 14.  The number of protons identifies the element that this tracer is an isotope of.  The number of neutrons in the element equals the number of protons, but in an isotope, the number of neutrons will be less than or greater than the number of protons.  Note, this differs from the 'atomic number' which indicates the number of protons only.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tracerlabel',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]), blank=True, default=list, help_text='The known labeled atom positions in the compound.  Note that the number of known labeled positions must be less than or equal to the labeled_count.', null=True, size=None),
        ),
    ]
