# Generated by Django 3.2.5 on 2021-10-15 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0007_tissue_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peakdata",
            name="med_mz",
            field=models.FloatField(
                blank=True,
                help_text="The median mass/charge value of this measurement.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="med_rt",
            field=models.FloatField(
                blank=True,
                help_text="The median retention time value of this measurement.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="raw_abundance",
            field=models.FloatField(
                blank=True,
                help_text="The ion count of this observation.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
