# Generated by Django 3.2.15 on 2023-03-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0006_alter_protocol_description'),
        ('DataRepo', '0007_alter_peakdatalabel_validators'),
    ]

    operations = [
    ]
