# Generated by Django 3.2.17 on 2023-04-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0007_alter_peakdatalabel_validators'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='infusatetracer',
            name='unique_infusate_tracer',
        ),
        migrations.AddConstraint(
            model_name='infusatetracer',
            constraint=models.UniqueConstraint(fields=('infusate', 'tracer'), name='unique_infusate_tracer'),
        ),
    ]
