# Generated by Django 3.2.20 on 2023-07-26 16:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0008_alter_infusate_tracer_uniq_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chromatographic_technique', models.CharField(choices=[('HILIC', 'HILIC'), ('Reverse Phase', 'Reverse Phase'), ('Other', 'Other')], help_text='Laboratory-defined type of the liquid chromatography method.', max_length=256, unique=True)),
                ('description', models.TextField(blank=True, help_text='Full text of the liquid chromatography method.', null=True)),
                ('run_length', models.DurationField(help_text='Time duration to complete the mass spectrometry sequence.', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))])),
            ],
            options={
                'verbose_name': 'liquid chromatography method',
                'verbose_name_plural': 'liquid chromatography methods',
                'ordering': ['chromatographic_technique'],
            },
        ),
        migrations.AddConstraint(
            model_name='lcmethod',
            constraint=models.UniqueConstraint(fields=('chromatographic_technique', 'description', 'run_length'), name='lcmethod_record_unique'),
        ),
        migrations.AddConstraint(
            model_name='lcmethod',
            constraint=models.CheckConstraint(check=models.Q(('chromatographic_technique__in', ['HILIC', 'Reverse Phase', 'Other'])), name='lcmethod_technique_valid'),
        ),
    ]
