# Generated by Django 3.2.20 on 2023-07-31 19:21

import DataRepo.models.archive_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0008_alter_infusate_tracer_uniq_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short code of data formats stored in ArchiveFile', max_length=32, unique=True)),
                ('name', models.CharField(help_text='Human readable name of the data format', max_length=256, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description of the data format', max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short code for types of data stored in ArchiveFile', max_length=32, unique=True)),
                ('name', models.CharField(help_text='Human readable name of the data type', max_length=256, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description of the data type', max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='The user specified file name', max_length=512)),
                ('checksum', models.CharField(help_text='The sha1 checksum', max_length=256, unique=True)),
                ('imported_timestamp', models.DateTimeField(auto_now_add=True, help_text='The timestamp for when the source datafile was imported.')),
                ('file_location', models.FileField(blank=True, help_text='The path the file on the filesystem', null=True, unique=True, upload_to=DataRepo.models.archive_file.data_type_path)),
                ('data_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataRepo.dataformat')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataRepo.datatype')),
            ],
        ),
    ]
