# Generated by Django 3.2.5 on 2021-10-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0008_null_original_peakdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundSynonym',
            fields=[
                ('name', models.CharField(help_text='A synonymous name for a compound that is a commonly used within the laboratory. (e.g. "palmitic acid", "hexadecanoic acid", "C16", and "palmitate" might also be synonyms for "C16:0").', max_length=256, primary_key=True, serialize=False, unique=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='DataRepo.compound')),
            ],
            options={
                'verbose_name': 'synonym',
                'verbose_name_plural': 'synonyms',
                'ordering': ['compound', 'name'],
            },
        ),
    ]
