# Generated by Django 3.1.8 on 2021-05-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0006_auto_20210503_1855'),
        ('DataRepo', '0009_auto_20210429_1433'),
    ]

    operations = [
    ]
