# Generated by Django 3.2.20 on 2023-08-02 15:43

import DataRepo.models.archive_file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0009_archivefile_dataformat_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefile',
            name='data_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataRepo.dataformat'),
        ),
        migrations.AlterField(
            model_name='archivefile',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataRepo.datatype'),
        ),
        migrations.AlterField(
            model_name='archivefile',
            name='file_location',
            field=models.FileField(blank=True, help_text='The path of the archived file on the filesystem', null=True, unique=True, upload_to=DataRepo.models.archive_file.data_type_path),
        ),
    ]
