# Generated by Django 3.2.5 on 2021-11-04 13:49

from django.db import migrations


def create_default_synonyms(apps, schema_editor):
    Compound = apps.get_model("DataRepo", "Compound")
    CompoundSynonym = apps.get_model("DataRepo", "CompoundSynonym")
    for compound in Compound.objects.all():
        (_primary_synonym, created) = CompoundSynonym.objects.get_or_create(
            name=compound.name, compound_id=compound.id
        )
        ucfirst_synonym = compound.name[0].upper() + compound.name[1:]
        (_secondary_synonym, created) = CompoundSynonym.objects.get_or_create(
            name=ucfirst_synonym, compound_id=compound.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0009_compound_synonym"),
    ]

    operations = [
        migrations.RunPython(create_default_synonyms),
    ]
