# Generated by Django 3.2.5 on 2021-11-18 21:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0010_default_compound_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DurationField(blank=True, help_text='The age of the animal at the time of sample collection.', null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tracer_compound',
            field=models.ForeignKey(blank=True, help_text='The compound which was used as the tracer (i.e. infusate). The tracer is the labeled compound that is infused into the animal.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='DataRepo.compound'),
        ),
    ]
