# Generated by Django 3.1.8 on 2021-05-04 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0010_merge_20210504_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peakdata",
            name="labeled_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of labeled atoms (M+) observed relative "
                "to the presumed compound referred to in the peak group.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
