# Generated by Django 3.2.20 on 2023-08-04 14:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0010_auto_20230802_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique laboratory-defined name of the liquid chromatography method.(e.g. HILIC-0:25:00 minutes, Reverse Phase-0:25:00 minutes)', max_length=256, unique=True)),
                ('type', models.CharField(help_text='Laboratory-defined type of the liquid chromatography method.(e.g. HILIC, Reverse Phase)', max_length=128)),
                ('description', models.TextField(help_text='Unique full-text description of the liquid chromatography method.', unique=True)),
                ('run_length', models.DurationField(blank=True, help_text=('Time duration to complete a sample run through the liquid chromatography method.',), null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))])),
            ],
            options={
                'verbose_name': 'liquid chromatography method',
                'verbose_name_plural': 'liquid chromatography methods',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='lcmethod',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='DataRepo_lcmethod_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='lcmethod',
            constraint=models.CheckConstraint(check=models.Q(('type', ''), _negated=True), name='DataRepo_lcmethod_type_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='lcmethod',
            constraint=models.CheckConstraint(check=models.Q(('description', ''), _negated=True), name='DataRepo_lcmethod_description_not_empty'),
        ),
    ]
