# Generated by Django 3.2.5 on 2022-01-04 20:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0011_age_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tracer_compound',
            field=models.ForeignKey(default=5, help_text='The compound which was used as the tracer (i.e. infusate). The tracer is the labeled compound that is infused into the animal.', on_delete=django.db.models.deletion.RESTRICT, to='DataRepo.compound'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='tracer_labeled_atom',
            field=models.CharField(choices=[('C', 'Carbon'), ('N', 'Nitrogen'), ('H', 'Hydrogen'), ('O', 'Oxygen'), ('S', 'Sulfur')], default='C', help_text='The type of atom that is labeled in the tracer compound (e.g. "C", "H", "O").', max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tracer_labeled_count',
            field=models.PositiveSmallIntegerField(default=6, help_text='The number of labeled atoms (M+) in the tracer compound supplied to this animal.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
