# Generated by Django 3.1.8 on 2021-05-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0011_peakdata_help_test"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compound",
            options={"ordering": ["name"]},
        ),
    ]
