# Generated by Django 3.2.20 on 2023-08-16 14:23

from django.core.management import call_command
from django.db import migrations, models

from DataRepo.models import LCMethod


def remove_old_lc_methods(apps, schema_editor):
    LCMethod.objects.all().delete()


def load_lc_methods_fixture(apps, schema_editor):
    call_command("loaddata", "lc_methods", app_label="DataRepo")


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0011_LCMethod_addition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lcmethod",
            name="name",
            field=models.CharField(
                help_text="Unique laboratory-defined name of the liquid chromatography method.(e.g. polar-HILIC-25-min)",
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lcmethod",
            name="type",
            field=models.CharField(
                help_text="Laboratory-defined type of the liquid chromatography method.(e.g. polar-HILIC)",
                max_length=128,
            ),
        ),
        # remove prior records
        migrations.RunPython(remove_old_lc_methods),
        # load new records
        migrations.RunPython(load_lc_methods_fixture),
    ]
