# Generated by Django 3.2.5 on 2022-03-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0011_age_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tracer_compound',
            field=models.ForeignKey(blank=True, help_text='The compound which was used as the tracer (i.e. infusate). The tracer is the labeled compound that is infused into the animal.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='animals', to='DataRepo.compound'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tissue',
            field=models.ForeignKey(help_text='The tissue type this sample was taken from.', on_delete=django.db.models.deletion.RESTRICT, related_name='samples', to='DataRepo.tissue'),
        ),
    ]
