# Generated by Django 4.2.4 on 2023-08-09 17:10

import DataRepo.models.archive_file
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0011_LCMethod_addition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivefile",
            name="file_location",
            field=models.FileField(
                blank=True,
                help_text="The path of the archived file on the filesystem",
                null=True,
                upload_to=DataRepo.models.archive_file.data_type_path,
            ),
        ),
    ]
