# Generated by Django 3.1.8 on 2021-05-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0012_auto_20210507_1847"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"verbose_name": "Animal", "verbose_name_plural": "Animals"},
        ),
        migrations.AlterModelOptions(
            name="compound",
            options={
                "ordering": ["name"],
                "verbose_name": "Compound",
                "verbose_name_plural": "Compounds",
            },
        ),
        migrations.AlterModelOptions(
            name="msrun",
            options={"verbose_name": "MS Run", "verbose_name_plural": "MS Runs"},
        ),
        migrations.AlterModelOptions(
            name="peakdata",
            options={
                "ordering": ["peak_group"],
                "verbose_name": "Peak Data",
                "verbose_name_plural": "Peak Data",
            },
        ),
        migrations.AlterModelOptions(
            name="peakgroup",
            options={
                "verbose_name": "Peak Group",
                "verbose_name_plural": "Peak Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="protocol",
            options={"verbose_name": "Protocol", "verbose_name_plural": "Protocols"},
        ),
        migrations.AlterModelOptions(
            name="sample",
            options={"verbose_name": "Sample", "verbose_name_plural": "Samples"},
        ),
        migrations.AlterModelOptions(
            name="study",
            options={
                "ordering": ["name"],
                "verbose_name": "Study",
                "verbose_name_plural": "Studies",
            },
        ),
        migrations.AlterModelOptions(
            name="tissue",
            options={"verbose_name": "Tissue", "verbose_name_plural": "Tissues"},
        ),
        migrations.AlterField(
            model_name="animal",
            name="tracer_compound",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="animals",
                to="DataRepo.compound",
            ),
        ),
        migrations.AlterField(
            model_name="compound",
            name="hmdb_id",
            field=models.CharField(max_length=11, unique=True, verbose_name="HMDB ID"),
        ),
        migrations.AlterField(
            model_name="msrun",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="msruns",
                to="DataRepo.sample",
            ),
        ),
    ]
