# Generated by Django 3.1.8 on 2021-05-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0013_auto_20210514_1603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={
                "ordering": ["name"],
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
            },
        ),
    ]
