# Generated by Django 3.2.20 on 2023-08-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0013_peakgroupset_to_archivefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcmethod',
            name='name',
            field=models.CharField(help_text='Unique laboratory-defined name of the liquid chromatography method.(e.g. polar-HILIC-25-min)', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='lcmethod',
            name='type',
            field=models.CharField(help_text='Laboratory-defined type of the liquid chromatography method.(e.g. polar-HILIC)', max_length=128),
        ),
    ]
