# Generated by Django 4.2.4 on 2023-08-10 18:37

import django.db.models.deletion
from django.db import migrations, models


def archive_file_from_filename(apps, schema_editor):
    PeakGroup = apps.get_model("DataRepo", "PeakGroup")
    ArchiveFile = apps.get_model("DataRepo", "ArchiveFile")

    for peakgroup in PeakGroup.objects.all():
        archive_file = ArchiveFile.objects.get(
            filename=peakgroup.peak_group_set.filename
        )
        peakgroup.archive_file = archive_file
        peakgroup.save()


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0013_peakgroupset_to_archivefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="peakgroup",
            name="archive_file",
            field=models.ForeignKey(
                null=True,
                blank=True,
                default=None,
                help_text="The data file from which this PeakGroup was imported.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
                to="DataRepo.archivefile",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(archive_file_from_filename),
        migrations.AlterField(
            model_name="peakgroup",
            name="peak_group_set",
            field=models.ForeignKey(
                help_text="The source file this PeakGroup came from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
                to="DataRepo.peakgroupset",
            ),
        ),
    ]
