# Generated by Django 3.2.20 on 2023-10-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0016_protocols_to_lcmethods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msrun',
            options={'ordering': ['date', 'researcher', 'sample__name', 'lc_method__name'], 'verbose_name': 'mass spectrometry run', 'verbose_name_plural': 'mass spectrometry runs'},
        ),
        migrations.RemoveConstraint(
            model_name='msrun',
            name='unique_msrun',
        ),
        migrations.RemoveField(
            model_name='msrun',
            name='protocol',
        ),
        migrations.AlterField(
            model_name='protocol',
            name='category',
            field=models.CharField(choices=[('animal_treatment', 'Animal Treatment')], help_text='Classification of the protocol, e.g. an animal treatment.', max_length=256),
        ),
        migrations.AddConstraint(
            model_name='msrun',
            constraint=models.UniqueConstraint(fields=('researcher', 'date', 'lc_method', 'sample'), name='unique_msrun'),
        ),
    ]
