# Generated by Django 4.2.4 on 2023-11-02 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0017_link_peakgroup_to_archive_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="MSRunSequence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "researcher",
                    models.CharField(
                        help_text="The name of the researcher who ran the mass spectrometer.",
                        max_length=256,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The date that the mass spectrometer was run."
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        choices=[
                            ("HILIC", "HILIC"),
                            ("QE", "QE"),
                            ("QE2", "QE2"),
                            ("QTOF", "QTOF"),
                        ],
                        help_text="The name of the mass spectrometer.",
                        max_length=6,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on this mass spectrometer run sequence.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "lc_method",
                    models.ForeignKey(
                        help_text="The liquid chromatography protocol that was used for this mass spectrometer run sequence.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="DataRepo.lcmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "mass spectrometry run sequence",
                "verbose_name_plural": "mass spectrometry run sequences",
                "ordering": ["date", "researcher", "instrument", "lc_method__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="msrunsequence",
            constraint=models.UniqueConstraint(
                fields=("researcher", "date", "instrument", "lc_method"),
                name="unique_msrunsequence",
            ),
        ),
    ]
