# Generated by Django 4.2.4 on 2023-11-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0018_msrunsequence_msrunsequence_unique_msrunsequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="MSRunSample",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ms_data_files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Any mass spectrometry data files (e.g. mzXML files) associated with this sample and sequence, (potentially associated with multiple different raw files for multiple scans of the same sample).",
                        null=True,
                        related_name="msrun_samples",
                        to="DataRepo.archivefile",
                    ),
                ),
                (
                    "msrun_sequence",
                    models.ForeignKey(
                        help_text="The series of sample injections in a batch run of the mass spec instrument.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="msrun_samples",
                        to="DataRepo.msrunsequence",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        help_text="A sample that was injected at least once during a mass spectrometer sequence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msrun_samples",
                        to="DataRepo.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "mass spectrometry run sample",
                "verbose_name_plural": "mass spectrometry samples",
                "ordering": ["msrun_sequence", "sample"],
            },
        ),
        migrations.AddConstraint(
            model_name="msrunsample",
            constraint=models.UniqueConstraint(
                fields=("msrun_sequence", "sample"), name="unique_msrunsample"
            ),
        ),
    ]
