# Generated by Django 4.2.4 on 2023-11-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0022_alter_msrunsample_ms_data_files"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="msrunsample",
            options={
                "ordering": ["msrun_sequence", "sample", "ms_raw_file", "ms_data_file"],
                "verbose_name": "mass spectrometry run sample",
                "verbose_name_plural": "mass spectrometry samples",
            },
        ),
        migrations.RemoveConstraint(
            model_name="msrunsample",
            name="unique_msrunsample",
        ),
        migrations.RemoveField(
            model_name="msrunsample",
            name="ms_data_files",
        ),
        migrations.AddField(
            model_name="msrunsample",
            name="ms_data_file",
            field=models.ForeignKey(
                blank=True,
                help_text="A file representing a subset of data extracted from the raw file (e.g. an mzXML file).",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="mz_to_msrunsamples",
                to="DataRepo.archivefile",
            ),
        ),
        migrations.AddField(
            model_name="msrunsample",
            name="ms_raw_file",
            field=models.ForeignKey(
                blank=True,
                help_text="A raw file (generated by an instrument) representing one of potentially multiple mass spectrometry runs of this sample.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="raw_to_msrunsamples",
                to="DataRepo.archivefile",
            ),
        ),
        migrations.AddField(
            model_name="msrunsample",
            name="polarity",
            field=models.CharField(
                blank=True,
                choices=[("negative", "negative"), ("positive", "positive")],
                help_text="The polarity mode of this mass spectrometry run.",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="msrunsample",
            constraint=models.UniqueConstraint(
                fields=("ms_data_file",), name="unique_ms_data_file"
            ),
        ),
        migrations.AddConstraint(
            model_name="msrunsample",
            constraint=models.UniqueConstraint(
                fields=(
                    "msrun_sequence",
                    "sample",
                    "polarity",
                    "ms_raw_file",
                    "ms_data_file",
                ),
                name="unique_msrunsample",
            ),
        ),
    ]
