# Generated by Django 3.2.20 on 2023-12-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0025_alter_msrunsample_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='peakgroup',
            name='unique_peakgroup',
        ),
        migrations.RemoveField(
            model_name='peakgroup',
            name='msrun',
        ),
        migrations.AddField(
            model_name='peakgroup',
            name='msrun_sample',
            field=models.ForeignKey(help_text='The MS Run this PeakGroup belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peak_groups', to='DataRepo.msrunsample'),
        ),
        migrations.AddConstraint(
            model_name='peakgroup',
            constraint=models.UniqueConstraint(fields=('name', 'msrun_sample'), name='unique_peakgroup'),
        ),
    ]
