# Generated by Django 4.2.4 on 2023-12-15 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0027_msrun_to_msrunsample_msrunsequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrunsample",
            name="polarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "unknown"),
                    ("positive", "positive"),
                    ("negative", "negative"),
                ],
                help_text="The polarity mode of this mass spectrometry run.",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="peakgroup",
            name="msrun_sample",
            field=models.ForeignKey(
                default=0,
                help_text="The MS Run this PeakGroup belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
                to="DataRepo.msrunsample",
            ),
            preserve_default=False,
        ),
    ]
