# Generated by Django 3.2.20 on 2024-01-13 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0029_study_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='msrunsample',
            name='unique_msrunsample',
        ),
        migrations.AddField(
            model_name='msrunsample',
            name='mz_max',
            field=models.FloatField(blank=True, help_text='Unsigned maximum charge of the scan range.  Only required if a study contains multiple MSRuns with the same polarity.  Automatically parsed from mzXML.  If unavailable, the maximum medMz value from the accucor/isocorr file is acceptable.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='msrunsample',
            name='mz_min',
            field=models.FloatField(blank=True, help_text='Unsigned minimum charge of the scan range.  Only required if a study contains multiple MSRuns with the same polarity.  Automatically parsed from mzXML.  If unavailable, the minimum medMz value from the accucor/isocorr file is acceptable.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='msrunsample',
            constraint=models.UniqueConstraint(fields=('msrun_sequence', 'sample', 'polarity', 'ms_raw_file', 'ms_data_file', 'mz_min', 'mz_max'), name='unique_msrunsample'),
        ),
    ]
