# Generated by Django 3.2.20 on 2024-01-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0030_auto_20240113_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeakGroupSet',
        ),
    ]
