# Generated by Django 3.2.20 on 2024-01-17 23:24

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0031_delete_peakgroupset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MSRun',
        ),
    ]
