# Generated by Django 3.2.20 on 2024-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataRepo', '0032_delete_msrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tissue',
            name='description',
            field=models.TextField(help_text='Description of this tissue type.'),
        ),
    ]
