# Generated by Django 4.2.4 on 2024-02-01 20:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0033_alter_tissue_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="time_collected",
            field=models.DurationField(
                blank=True,
                help_text="The time, relative to an infusion timepoint, that a sample was extracted from an animal.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(days=-1)
                    ),
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(days=90)
                    ),
                ],
            ),
        ),
    ]
