# Generated by Django 4.2.10 on 2024-02-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataRepo", "0034_alter_tissue_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrunsequence",
            name="instrument",
            field=models.CharField(
                choices=[
                    ("QE", "Q Exactive"),
                    ("QE2", "Q Exactive 2"),
                    ("QEPlus", "Q Exactive Plus"),
                    ("QEHF", "Q Exactive HF"),
                    ("Exploris240", "Exploris 240"),
                    ("Exploris480", "Exploris 480"),
                    ("ExplorisMX", "Exploris MX"),
                    ("unknown", "Unknown"),
                ],
                help_text="The name of the mass spectrometer.",
                max_length=32,
            ),
        ),
    ]
