# Initially generated by Django 4.2.11 on 2024-04-13 12:36, then modified

from django.db import migrations, models
import django.db.models.deletion

from DataRepo.models.hier_cached_model import (
    disable_caching_updates,
    enable_caching_updates,
)

def update_peakgroup_sample_msrun_and_sequence(apps, _):
    """Initializes PeakGroup.sample, PeakGroup.msrun_sequence, and sets PeakGroup.msrun_sample to None if
    PeakGroup.msrun_sample.ms_data_file is None"""

    # We retrieve the models using an "apps" registry, which contains historical versions of all of the models, because
    # the current version may be newer than this migration expects.
    PeakGroup = apps.get_model("DataRepo", "PeakGroup")

    disable_caching_updates()
    for pg in PeakGroup.objects.all():
        pg.sample = pg.msrun_sample.sample
        pg.msrun_sequence = pg.msrun_sample.msrun_sequence
        if pg.msrun_sample.ms_data_file is None:
            pg.msrun_sample = None
        pg.full_clean()
        pg.save()
    enable_caching_updates()

def remove_msrunsample_recs_with_no_mzxml(apps, _):
    """Removes MSRunSample records that have no mzxml file."""

    # We retrieve the models using an "apps" registry, which contains historical versions of all of the models, because
    # the current version may be newer than this migration expects.
    MSRunSample = apps.get_model("DataRepo", "MSRunSample")

    disable_caching_updates()
    MSRunSample.objects.filter(ms_data_file__isnull=True).delete()
    enable_caching_updates()


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0036_update_instruments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peakgroup",
            name="msrun_sample",
            field=models.ForeignKey(
                blank=True,
                help_text="The MS Run this PeakGroup came from.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
                to="DataRepo.msrunsample",
            ),
        ),

        # Add sample field initially as null=True
        migrations.AddField(
            model_name='peakgroup',
            name='sample',
            field=models.ForeignKey(
                to="DataRepo.Sample",
                blank=True,
                help_text='The sample this PeakGroup came from.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
            ),
        ),

        # Add msrun_sequence field initially as null=True
        migrations.AddField(
            model_name='peakgroup',
            name='msrun_sequence',
            field=models.ForeignKey(
                to="DataRepo.MSRunSequence",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="peak_groups",
                help_text="The mass spec batch sequence from which this peak group was derived.",
            ),
        ),

        # Fill in values for the sample and msrun_sequence fields, using the existing msrun_sample references
        migrations.RunPython(update_peakgroup_sample_msrun_and_sequence),

        # Change sample field to null=False
        migrations.AlterField(
            model_name='peakgroup',
            name='sample',
            field=models.ForeignKey(
                to="DataRepo.Sample",
                blank=False,
                help_text='The sample this PeakGroup came from.',
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peak_groups",
            ),
        ),

        # Change msrun_sequence field to null=False
        migrations.AlterField(
            model_name='peakgroup',
            name='msrun_sequence',
            field=models.ForeignKey(
                to="DataRepo.MSRunSequence",
                null=False,
                blank=False,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="peak_groups",
                help_text="The mass spec batch sequence from which this peak group was derived.",
            ),
        ),

        # Remove MSRunSample records when ms_data_file is None
        migrations.RunPython(remove_msrunsample_recs_with_no_mzxml),
    ]
