# Generated by Django 4.2.11 on 2024-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0036_update_instruments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="msrunsample",
            options={
                "ordering": [
                    "msrun_sequence",
                    "sample",
                    "ms_raw_file__filename",
                    "ms_data_file__filename",
                ],
                "verbose_name": "mass spectrometry run sample",
                "verbose_name_plural": "mass spectrometry samples",
            },
        ),
        migrations.RemoveConstraint(
            model_name="msrunsample",
            name="unique_ms_data_file",
        ),
        migrations.RemoveConstraint(
            model_name="msrunsample",
            name="unique_msrunsample",
        ),
        migrations.AddConstraint(
            model_name="msrunsample",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ms_data_file__isnull", True)),
                fields=("msrun_sequence", "sample"),
                name="unique_msrunsample_placeholder",
            ),
        ),
        migrations.AddConstraint(
            model_name="msrunsample",
            constraint=models.UniqueConstraint(
                fields=("ms_data_file",), name="unique_msrunsample"
            ),
        ),
    ]
