# Generated by Django 4.2.11 on 2024-06-17 02:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0038_alter_msrunsample_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="time_collected",
            field=models.DurationField(
                blank=True,
                help_text="The time, relative to an infusion timepoint, that a sample was extracted from an animal.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(days=-1),
                        message="Sample.time_collected must be greater than or equal to -1 day, 0:00:00.",
                    ),
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(days=90),
                        message="Sample.time_collected must be less than or equal to 90 days, 0:00:00.",
                    ),
                ],
            ),
        ),
    ]
