# Generated by Django 4.2.11 on 2024-06-24 12:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0039_alter_sample_time_collected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lcmethod",
            name="run_length",
            field=models.DurationField(
                blank=True,
                help_text="Time duration to complete a sample run through the liquid chromatography method.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.timedelta(0)),
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(days=1)
                    ),
                ],
            ),
        ),
    ]
