# Generated by Django 4.2.11 on 2024-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0041_alter_protocol_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peakgroup",
            name="name",
            field=models.CharField(
                help_text="Peak group name, composed of 1 or more compound synonyms, delimited by '/', e.g. 'citrate/isocitrate'.  (Note, synonym(s) may confer information about the compound that is not recorded in the compound record, such as a specific stereoisomer.)",
                max_length=256,
            ),
        ),
    ]
