# Generated by Django 4.2.11 on 2024-08-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0041_alter_protocol_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="study",
            name="code",
        ),
    ]
