# Generated by Django 4.2.11 on 2025-02-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0044_alter_animal_infusate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivefile",
            options={
                "ordering": [
                    "filename",
                    "data_type__name",
                    "data_format__name",
                    "imported_timestamp",
                ],
                "verbose_name": "Archive File",
                "verbose_name_plural": "Archive Files",
            },
        ),
    ]
