# Generated by Django 4.2.16 on 2025-03-06 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0045_alter_archivefile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infusate",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name": "infusate",
                "verbose_name_plural": "infusates",
            },
        ),
        migrations.AlterModelOptions(
            name="tracer",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name": "tracer",
                "verbose_name_plural": "tracers",
            },
        ),
        migrations.AddField(
            model_name="tracer",
            name="label_combo",
            field=models.CharField(
                editable=False,
                help_text="The tracer's ordered combination of elements, delimited by '+'.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="body_weight",
            field=models.FloatField(
                blank=True,
                help_text="The weight (in grams) of the animal at the time of sample collection.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Weight (g)",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="feeding_status",
            field=models.CharField(
                blank=True,
                help_text="The laboratory coded dietary state for the animal, also referred to as 'Animal State' (e.g. 'fasted').",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="infusion_rate",
            field=models.FloatField(
                blank=True,
                help_text="The rate of infusion of the tracer solution in microliters/min/gram of body weight of the animal (ul/min/g).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Infusion Rate (ul/min/g)",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="last_serum_sample",
            field=models.ForeignKey(
                blank=True,
                db_column="last_serum_sample_id",
                help_text="Automatically maintained field.  Shortcut to the last serum sample.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="animals",
                to="DataRepo.sample",
            ),
        ),
        migrations.AlterField(
            model_name="infusatetracer",
            name="concentration",
            field=models.FloatField(
                help_text="The millimolar concentration of the tracer in a specific infusate 'recipe' (mM).",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tracer Concentration (mM)",
            ),
        ),
    ]
