# Generated by Django 4.2.16 on 2025-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0046_alter_infusate_options_alter_tracer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infusate",
            name="label_combo",
            field=models.CharField(
                editable=False,
                help_text="The infusate's unique ordered combination of elements by tracer, delimited by ', '.",
                max_length=16,
                null=True,
                verbose_name="Tracer Label Combos",
            ),
        ),
    ]
