# Generated by Django 4.2.16 on 2025-03-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0047_infusate_label_combo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infusate",
            name="label_combo",
            field=models.CharField(
                editable=False,
                help_text="The infusate's unique ordered combination of elements by tracer, delimited by ', '.",
                max_length=32,
                null=True,
                verbose_name="Tracer Label Combos",
            ),
        ),
    ]
