# Generated by Django 4.2.16 on 2025-03-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0049_animal_label_combo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="label_combo",
        ),
        migrations.AlterField(
            model_name="sample",
            name="researcher",
            field=models.CharField(
                help_text='The name of the researcher who prepared the sample (e.g. "Alex Medina").',
                max_length=256,
                verbose_name="Sample Owner",
            ),
        ),
    ]
