# Generated by Django 4.2.16 on 2025-03-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0050_remove_animal_label_combo_alter_sample_researcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="label_combo",
            field=models.CharField(
                editable=False,
                help_text="The infusate's unique ordered combination of elements by tracer, e.g. 'C, C+N'.",
                max_length=32,
                null=True,
                verbose_name="Tracer Label Combos",
            ),
        ),
    ]
