# Generated by Django 4.2.20 on 2025-06-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0051_animal_label_combo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infusatetracer",
            name="tracer",
            field=models.ForeignKey(
                help_text="A tracer belonging to an infusate.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infusate_links",
                to="DataRepo.tracer",
            ),
        ),
        migrations.AlterField(
            model_name="tracer",
            name="compound",
            field=models.ForeignKey(
                help_text="A compound used as a tracer, containing some elements replaced with isotopes.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tracers",
                to="DataRepo.compound",
            ),
        ),
    ]
