# Generated by Django 4.2.20 on 2025-06-24 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0052_alter_infusatetracer_tracer_alter_tracer_compound"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="animal",
            field=models.ForeignKey(
                help_text="The source animal from which a sample was extracted.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="DataRepo.animal",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="The date a sample was collected.",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="is_serum_sample",
            field=models.BooleanField(
                default=False,
                help_text="This field indicates whether a sample is a serum sample.",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(
                help_text="The unique name of a biological sample.",
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="researcher",
            field=models.CharField(
                help_text='The name of the researcher who prepared a sample (e.g. "Alex Medina").',
                max_length=256,
                verbose_name="Sample Owner",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="tissue",
            field=models.ForeignKey(
                help_text="The tissue type a sample was taken from.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="samples",
                to="DataRepo.tissue",
            ),
        ),
    ]
