# Generated by Django 4.2.20 on 2025-07-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0053_alter_sample_animal_alter_sample_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivefile",
            name="data_format",
            field=models.ForeignKey(
                help_text="A description of how data is organized, usually associated with a specific tool version that generated it, e.g. 'AccuCor'.",
                on_delete=django.db.models.deletion.PROTECT,
                to="DataRepo.dataformat",
                verbose_name="Data Format",
            ),
        ),
        migrations.AlterField(
            model_name="archivefile",
            name="data_type",
            field=models.ForeignKey(
                help_text="A categorization of data, e.g. 'raw mass spectrometry data'.",
                on_delete=django.db.models.deletion.PROTECT,
                to="DataRepo.datatype",
                verbose_name="Data Type",
            ),
        ),
    ]
