# Generated by Django 4.2.20 on 2025-07-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0054_alter_archivefile_data_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="label_combo",
            field=models.CharField(
                editable=False,
                help_text="The infusate's unique ordered combination of elements by tracer, e.g. 'C, C+N'.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="msrunsequence",
            name="researcher",
            field=models.CharField(
                help_text="The name of the researcher who ran the mass spectrometer.",
                max_length=256,
                verbose_name="MSRun Operator",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A long form description for a study which may include the experimental design process, citations, and other relevant details.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="name",
            field=models.CharField(
                help_text="A succinct name for a study, which is a collection of one or more animals and their data.",
                max_length=256,
                unique=True,
            ),
        ),
    ]
