# Generated by Django 4.2.20 on 2025-07-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0055_alter_animal_label_combo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lcmethod",
            options={
                "ordering": ["name"],
                "verbose_name": "LC Protocol",
                "verbose_name_plural": "LC Protocols",
            },
        ),
        migrations.AlterField(
            model_name="msrunsequence",
            name="lc_method",
            field=models.ForeignKey(
                help_text="The liquid chromatography protocol that was used for this mass spectrometer run sequence.",
                on_delete=django.db.models.deletion.RESTRICT,
                to="DataRepo.lcmethod",
                verbose_name="LC Protocol",
            ),
        ),
    ]
