# Generated by Django 4.2.20 on 2025-07-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0052_alter_compound_formula_alter_compound_name_and_more"),
        ("DataRepo", "0056_alter_lcmethod_options_alter_msrunsequence_lc_method"),
    ]

    operations = []
