# Generated by Django 4.2.20 on 2025-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0056_alter_lcmethod_options_alter_msrunsequence_lc_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="animals_by_tracer",
            field=models.IntegerField(
                blank=True,
                help_text="The total number of animals infused with a tracer based on this parent compound.",
                null=True,
            ),
        ),
    ]
