# Generated by Django 4.2.20 on 2025-07-18 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0057_compound_animals_by_tracer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peakdata",
            name="med_mz",
            field=models.FloatField(
                blank=True,
                help_text="The median mass to charge ratio of an ion expressed in atomic mass units divided by a positive integer representing the number of gained or lost electrons.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Median Mass to Charge Ratio (m/z)",
            ),
        ),
        migrations.AlterField(
            model_name="peakdata",
            name="med_rt",
            field=models.FloatField(
                blank=True,
                help_text="The median retention time of a compound to pass through the chromatography column, in minutes.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Median Retention Time (m)",
            ),
        ),
    ]
