# Generated by Django 4.2.20 on 2025-07-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0057_merge_20250729_1749"),
        ("DataRepo", "0058_alter_peakdata_med_mz_alter_peakdata_med_rt"),
    ]

    operations = []
