# Generated by Django 4.2.20 on 2025-07-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0057_merge_20250729_1420"),
        ("DataRepo", "0059_merge_20250730_1834"),
    ]

    operations = []
