# Generated by Django 4.2.29 on 2026-03-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0060_merge_20250731_1350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrunsequence",
            name="lc_method",
            field=models.ForeignKey(
                help_text="The liquid chromatography protocol that was used for this mass spectrometer run sequence.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="msrun_sequences",
                to="DataRepo.lcmethod",
                verbose_name="LC Protocol",
            ),
        ),
    ]
