# Generated by Django 4.2.21 on 2025-12-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0060_merge_20250731_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="peakgroup",
            name="total_abundance",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text='Sum of the corrected abundances of all peak data for this compound.  AccuCor provides this in the tab "pool size".',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="peakgrouplabel",
            name="enrichment_fraction",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="A weighted average of the fraction of labeled atoms for this peak group in this sample with this labeled element.  E.g. The fraction of carbons that are labeled in this peak group compound.  I.e. Sum (fraction * count) / num_atoms(element)",
                null=True,
            ),
        ),
    ]
