# Generated by Django 4.2.29 on 2026-06-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0061_alter_msrunsequence_lc_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrunsequence",
            name="instrument",
            field=models.CharField(
                choices=[
                    ("QE", "Q Exactive"),
                    ("QE2", "Q Exactive 2"),
                    ("QEPlus", "Q Exactive Plus"),
                    ("QEHF", "Q Exactive HF"),
                    ("Exploris240", "Exploris 240"),
                    ("Exploris480", "Exploris 480"),
                    ("ExplorisMX", "Exploris MX"),
                    ("OrbitrapExploris240", "Orbitrap Exploris 240"),
                    ("OrbitrapExploris480", "Orbitrap Exploris 480"),
                    ("unknown", "Unknown"),
                ],
                help_text="The name of the mass spectrometer.",
                max_length=32,
            ),
        ),
    ]
