# Generated by Django 4.2.27 on 2026-06-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataRepo", "0061_alter_msrunsequence_lc_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msrunsequence",
            name="instrument",
            field=models.CharField(
                choices=[
                    ("QE", "Q Exactive"),
                    ("QE2", "Q Exactive 2"),
                    ("QEPlus", "Q Exactive Plus"),
                    ("QEHF", "Q Exactive HF"),
                    ("Exploris240", "Exploris 240"),
                    ("Exploris480", "Exploris 480"),
                    ("ExplorisMX", "Exploris MX"),
                    ("LTQ", "LTQ"),
                    ("LTQFT", "LTQ FT"),
                    ("LTQFTUltra", "LTQ FT Ultra"),
                    ("LTQOrbitrap", "LTQ Orbitrap"),
                    ("LTQOrbitrapXL", "LTQ Orbitrap XL"),
                    ("LTQOrbitrapDiscovery", "LTQ Orbitrap Discovery"),
                    ("LTQOrbitrapVelos", "LTQ Orbitrap Velos"),
                    ("LTQOrbitrapVelosPro", "LTQ Orbitrap Velos Pro"),
                    ("LTQOrbitrapElite", "LTQ Orbitrap Elite"),
                    ("LTQXL", "LTQ XL"),
                    ("LTQVelos", "LTQ Velos"),
                    ("LTQVelosPro", "LTQ Velos Pro"),
                    ("LXQ", "LXQ"),
                    ("LCQAdvantage", "LCQ Advantage"),
                    ("LCQDeca", "LCQ Deca"),
                    ("LCQDecaXPPlus", "LCQ Deca XP Plus"),
                    ("TSQQuantum", "TSQ Quantum"),
                    ("TSQQuantumUltra", "TSQ Quantum Ultra"),
                    ("TSQQuantumAccess", "TSQ Quantum Access"),
                    ("TSQVantage", "TSQ Vantage"),
                    ("TSQEndura", "TSQ Endura"),
                    ("TSQQuantiva", "TSQ Quantiva"),
                    ("Exactive", "Exactive"),
                    ("OrbitrapFusion", "Orbitrap Fusion"),
                    ("OrbitrapFusionLumos", "Orbitrap Fusion Lumos"),
                    ("OrbitrapExploris120", "Orbitrap Exploris 120"),
                    ("OrbitrapExploris240", "Orbitrap Exploris 240"),
                    ("OrbitrapExploris480", "Orbitrap Exploris 480"),
                    ("LTQOrbitrapVelosETD", "LTQ Orbitrap Velos ETD"),
                    ("LTQOrbitrapXLETD", "LTQ Orbitrap XL ETD"),
                    ("OrbitrapFusionTribrid", "Orbitrap Fusion Tribrid"),
                    (
                        "QEHF-XHybridQuadrupole-Orbitrap",
                        "Q Exactive HF-X Hybrid Quadrupole-Orbitrap",
                    ),
                    ("ThermoFinniganLTQ", "Thermo Finnigan LTQ"),
                    ("ThermoScientificQE", "Thermo Scientific Q Exactive"),
                    ("unknown", "Unknown"),
                ],
                help_text="The name of the mass spectrometer.",
                max_length=32,
            ),
        ),
    ]
