site_name: TraceBase Documentation
site_url: http://Princeton-LSI-ResearchComputing.github.io/tracebase
site_dir: public
docs_dir: ./TraceBaseDocs

theme: readthedocs

plugins:
  - search
  - roamlinks
