from django.urls import path

from .views import (
    AdvancedSearchDownloadMzxmlZIPView,
    AdvancedSearchDownloadView,
    AdvancedSearchView,
    AnimalDetailView,
    AnimalListView,
    AnimalTreatmentListView,
    ArchiveFileDetailView,
    ArchiveFileListView,
    BuildSubmissionView,
    CompoundDetailView,
    CompoundListView,
    InfusateDetailView,
    InfusateListView,
    LCMethodDetailView,
    LCMethodListView,
    MSRunSampleDetailView,
    MSRunSampleListView,
    MSRunSequenceDetailView,
    MSRunSequenceListView,
    PeakDataListView,
    PeakGroupDetailView,
    PeakGroupListView,
    ProtocolDetailView,
    SampleDetailView,
    SampleListView,
    StudyDetailView,
    StudyListView,
    TissueDetailView,
    TissueListView,
    home,
    search_basic,
    study_summary,
    view_search_results,
)

urlpatterns = [
    path("", home, name="home"),
    path("submission", BuildSubmissionView.as_view(), name="submission"),
    path(
        "search_basic/<str:mdl>/<str:fld>/<str:cmp>/<str:val>/<str:fmt>/",
        search_basic,
        name="search_basic",
    ),
    path(
        "static_search_results/",
        view_search_results,
        name="view_search_results",
    ),
    path(
        "search_advanced/",
        AdvancedSearchView.as_view(),
        name="search_advanced",
    ),
    path(
        "search_advanced_tsv/",
        AdvancedSearchDownloadView.as_view(),
        name="search_advanced_tsv",
    ),
    path(
        "search_advanced_mzxml/",
        AdvancedSearchDownloadMzxmlZIPView.as_view(),
        name="search_advanced_mzxml",
    ),
    path("compounds/", CompoundListView.as_view(), name="compound_list"),
    path(
        "compounds/<int:pk>/",
        CompoundDetailView.as_view(),
        name=CompoundDetailView.model.detail_name,
    ),
    path("studies/", StudyListView.as_view(), name="study_list"),
    path(
        "studies/<int:pk>/",
        StudyDetailView.as_view(),
        name=StudyDetailView.model.detail_name,
    ),
    path("studies/study_summary/", study_summary, name="study_summary"),
    path(
        "protocols/animal_treatments/",
        AnimalTreatmentListView.as_view(),
        name="animal_treatment_list",
    ),
    path(
        "protocols/<int:pk>/",
        ProtocolDetailView.as_view(),
        name=ProtocolDetailView.model.detail_name,
    ),
    path(
        "lcprotocols/",
        LCMethodListView.as_view(),
        name="lcmethod_list",
    ),
    path(
        "lcprotocols/<int:pk>/",
        LCMethodDetailView.as_view(),
        name=LCMethodDetailView.model.detail_name,
    ),
    path("animals/", AnimalListView.as_view(), name="animal_list"),
    path(
        "animals/<int:pk>/",
        AnimalDetailView.as_view(),
        name=AnimalDetailView.model.detail_name,
    ),
    path("tissues/", TissueListView.as_view(), name="tissue_list"),
    path(
        "tissues/<int:pk>/",
        TissueDetailView.as_view(),
        name=TissueDetailView.model.detail_name,
    ),
    path("samples/", SampleListView.as_view(), name="sample_list"),
    path(
        "samples/<int:pk>/",
        SampleDetailView.as_view(),
        name=SampleDetailView.model.detail_name,
    ),
    path("msrunsamples/", MSRunSampleListView.as_view(), name="msrunsample_list"),
    path(
        "msrunsamples/<int:pk>/",
        MSRunSampleDetailView.as_view(),
        name=MSRunSampleDetailView.model.detail_name,
    ),
    path(
        "msrunsequences/",
        MSRunSequenceListView.as_view(),
        name="msrunsequence_list",
    ),
    path(
        "msrunsequences/<int:pk>/",
        MSRunSequenceDetailView.as_view(),
        name=MSRunSequenceDetailView.model.detail_name,
    ),
    path(
        "archive_files/",
        ArchiveFileListView.as_view(),
        name="archive_file_list",
    ),
    path(
        "archive_file/<int:pk>/",
        ArchiveFileDetailView.as_view(),
        name=ArchiveFileDetailView.model.detail_name,
    ),
    path("peakgroups/", PeakGroupListView.as_view(), name="peakgroup_list"),
    path(
        "peakgroups/<int:pk>/",
        PeakGroupDetailView.as_view(),
        name=PeakGroupDetailView.model.detail_name,
    ),
    path("peakdata/", PeakDataListView.as_view(), name="peakdata_list"),
    path("infusates/", InfusateListView.as_view(), name="infusate_list"),
    path(
        "infusates/<int:pk>/",
        InfusateDetailView.as_view(),
        name=InfusateDetailView.model.detail_name,
    ),
]
