import os
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional, cast

from django.utils.text import get_valid_filename

from DataRepo.models import Study
from DataRepo.utils.export_base import ExportBase


class ExportsOrganizer(ExportBase):
    """A class defining operations to take an export directory containing previously exported data as generated by
    StudiesExporter and organizes it into zip archives at various granularities (all together, by study, and by data
    type).  It is designed to generate these zip archives by host and export date.

    Class Attributes:
        allstudies_str (str): A string included in the zip archive names indicating that all studies are included in the
            file.
        alldatatypes_str (str): A string included in the zip archive names indicating that all data types are included
            in the file.
    Instance Attributes:
        slugified_study_names (Dict[int, str]): Study ID keys mapped to slugified study names.
        export_dir (str): The path to the existing output directory.
        staging_mode (bool) [False]: Write outputs as .staged files and publish them (and staged files produced by
            StudiesExporter.export()) by renaming them to their final names when processing completes.
    """

    allstudies_str = "allstudies"
    alldatatypes_str = "alldatatypes"

    def __init__(self):
        self.slugified_study_names = self.get_slugified_study_names_dict()
        self.export_dir: str
        self.staging_mode = False

    @classmethod
    def get_slugified_study_names_dict(cls):
        """Returns a dict of slugified study names suitable for inclusion in a dash-delimited filename.

        Args:
            None
        Exceptions:
            None
        Returns:
            (Dict[int, str]): Study ID keys mapped to slugified study names.
        """
        return dict(
            (
                rec.id,
                get_valid_filename(rec.name).replace("-", "_"),
            )
            for rec in Study.objects.all()
        )

    def organize(self, export_dir: str, staging_mode=False):
        """Takes an export directory containing previously exported data as generated by StudiesExporter and organizes
        it into zip archives at various granularities (all together, by study, and by data type).  It is designed to
        generate these zip archives by export date.

        It removes exports that have not changed, thereby keeping only those exported files that differ from the
        previous kept export.  Zip archives are created whenever any 1 export file has changed compared to its previous
        version, and the latest version of every other export file is included in the archive.  I.e. Only unique export
        versions are retained once they have been organized.

        It also leaves the individual files intact (as long as they differ from previous exports).

        This method should be called immediately after StudiesExporter.export().

        The files contained must be named in the following ways:

        As output by StudiesExporter.export():
            Individually               Filename: {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{ext}
        As previously organized by this method:
            All studies and datatypes  Filename: {hostname}-{datestamp}-allstudies-alldatatypes.zip
            All studies by datatype    Filename: {hostname}-{datestamp}-allstudies-{data_type}.zip
            All datatypes by study     Filename: {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip

        Example:
            Exported files prior to organization:
                tracebase-2026.04.17-acute_stress-0035-PeakData.tsv
                tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv
                tracebase-2026.04.17-acute_stress-0035-FCirc.tsv
                tracebase-2026.04.17-acute_stress-0035-mzXML.zip
                tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip  # By study, 2026.04.17
                tracebase-2026.04.17-allstudies-alldatatypes.zip         # All together, 2026.04.17
                tracebase-2026.04.17-allstudies-PeakData.zip             # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-PeakGroups.zip           # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-FCirc.zip                # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-mzXML.zip                # By data type, 2026.04.17
                tracebase-2026.04.24-acute_stress-0035-PeakData.tsv      # Same - will be deleted
                tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv    # Same - will be deleted
                tracebase-2026.04.24-acute_stress-0035-FCirc.tsv         # Differs from the 2026.04.17 version
                tracebase-2026.04.24-acute_stress-0035-mzXML.zip         # Same - will be deleted
            Exported files after organization:
                tracebase-2026.04.17-acute_stress-0035-PeakData.tsv      # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv    # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-FCirc.tsv         # NOT included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-mzXML.zip         # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip
                tracebase-2026.04.17-allstudies-alldatatypes.zip
                tracebase-2026.04.17-allstudies-PeakData.zip
                tracebase-2026.04.17-allstudies-PeakGroups.zip
                tracebase-2026.04.17-allstudies-FCirc.zip
                tracebase-2026.04.17-allstudies-mzXML.zip
                tracebase-2026.04.24-acute_stress-0035-FCirc.tsv         # Only one kept from the latest export
                tracebase-2026.04.24-allstudies-alldatatypes.zip         # New file
                tracebase-2026.04.24-allstudies-PeakData.zip             # New file
                tracebase-2026.04.24-allstudies-PeakGroups.zip           # New file
                tracebase-2026.04.24-allstudies-FCirc.zip                # New file
                tracebase-2026.04.24-allstudies-mzXML.zip                # New file
                tracebase-2026.04.24-acute_stress-0035-alldatatypes.zip  # New file
        Args:
            export_dir (str): The path to the existing output directory.
            staging_mode (bool) [False]: Write outputs as .staged files and publish them (and staged files produced by
                StudiesExporter.export()) by renaming them to their final names when processing completes.
        Exceptions:
            None
        Returns:
            None
        """
        self.export_dir = export_dir
        self.staging_mode = staging_mode

    @classmethod
    def parse_export_filename(cls, filepath: str):
        """Takes a filepath and returns a tuple of the file name components.

        Examples:
            "tracebase-2026.04.17-acute_stress-0035-FCirc.tsv"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "FCirc", ".tsv")

            "tracebase-2026.04.17-acute_stress-0035-mzXML.zip"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "mzXML", ".zip")

            "tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "alldatatypes", ".zip")

            "tracebase-2026.04.17-allstudies-alldatatypes.zip"
            -> ("tracebase", "2026.04.17", "allstudies", None, "alldatatypes", ".zip")

            "tracebase-2026.04.17-allstudies-PeakData.zip"
            -> ("tracebase", "2026.04.17", "allstudies", None, "PeakData", ".zip")
        Args:
            filename (str)
        Exceptions:
            ExportParseError
        Returns:
            host (str): hostname, e.g. "tracebase"
            date_str (str): Date, E.g. "2026.04.17"
            slugged_study_name (str): Study name, as parsed from the file, e.g. "acute_stress".  This can have a special
                value of "allstudies" (as parsed from the file).
            study_id (Optional[str]): A 4-digit study ID with leading zeroes, e.g. "0035".  This will be None in the
                event that the file is a combination of studies.
            data_type (str): Data type, e.g. "PeakData".  This can have a special value of "alldatatypes" (as parsed
                from the file).
            ext (str): File extension (no dot)
        """
        study_id: Optional[str]

        filenameext = os.path.basename(filepath)
        filename: str
        filename, ext = os.path.splitext(filenameext)

        if ext == cls.staged_ext:
            staged = True
            filename, ext = os.path.splitext(filename)
        else:
            staged = False

        fn_components = filename.split("-")
        if len(fn_components) == 4 and (
            fn_components[2] == cls.allstudies_str
            or fn_components[3] == cls.alldatatypes_str
        ):
            study_id = None
            host, date_str, slugged_study_name, data_type = fn_components
        elif len(fn_components) == 5:
            host, date_str, slugged_study_name, study_id, data_type = fn_components
        else:
            raise ExportParseError(filename)

        return (host, date_str, slugged_study_name, study_id, data_type, ext, staged)

    def compute_all_package_filename(self, host: str, package_date: str):
        """Given the host name and the package date, returns a zip archive filename representing all data exported on or
        before a given date and host.

        Assumptions:
            1. None of the arguments contain dashes.  The date is assumed to have been formatted with dots and the host
               is assumpd to have had dashes converted to underscores, each of which happens before we get here.
        Args:
            host (str)
            package_date (str)
        Exceptions:
            ValueError: If any argument contains a dash.
        Returns:
            (str): The name of the all export data archive file (for a given host and export date)
        """
        if "-" in host or "-" in package_date:
            raise ValueError(
                f"Arguments may not contain dashes ('{host}', '{package_date}' were supplied)."
            )

        if self.staging_mode:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip{self.staged_ext}"
        else:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip"

        return "-".join(
            [host, package_date, self.allstudies_str, alldatatypes_with_ext]
        )

    def compute_study_package_filename(
        self, host: str, package_date: str, study_key: str
    ):
        """Given the host name, the package date, and a study key (with leading zeroes), returns a zip archive filename
        representing all data exported for a particular study on or before a given date and host.

        Assumptions:
            1. None of the arguments contain dashes.  The date is assumed to have been formatted with dots, the host is
               assumed to have had dashes converted to underscores, and the study key is assumed to have had dashes and
               spaces converted to underscores, all of which happens before we get here.
        Args:
            host (str)
            package_date (str)
            study_key (str): E.g. "0003"
        Exceptions:
            ValueError: If any argument contains a dash.
        Returns:
            (str): The name of the all export data archive file (for a given host and export date)
        """
        if "-" in host or "-" in package_date:
            raise ValueError(
                f"Arguments may not contain dashes ('{host}', '{package_date}' were supplied)."
            )
        study_id = int(study_key)

        if self.staging_mode:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip{self.staged_ext}"
        else:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip"

        return "-".join(
            [
                host,
                package_date,
                self.slugified_study_names[study_id],
                alldatatypes_with_ext,
            ]
        )

    def compute_datatype_package_filename(
        self, host: str, package_date: str, data_type: str
    ):
        """Given the host name, the package date, and a study key (with leading zeroes), returns a zip archive filename
        representing all data exported for a particular study on or before a given date and host.

        Assumptions:
            1. None of the arguments contain dashes.  The date is assumed to have been formatted with dots, the host is
               assumed to have had dashes converted to underscores, and the study key is assumed to have had dashes and
               spaces converted to underscores, all of which happens before we get here.
        Args:
            host (str)
            package_date (str)
            study_key (str): E.g. "0003"
        Exceptions:
            ValueError: If any argument contains a dash.
        Returns:
            (str): The name of the all export data archive file (for a given host and export date)
        """
        if "-" in host or "-" in package_date or "-" in data_type:
            raise ValueError(
                "Arguments may not contain dashes "
                f"('{host}', '{package_date}', '{data_type}' were supplied)."
            )

        if self.staging_mode:
            data_type_with_ext = f"{data_type}.zip{self.staged_ext}"
        else:
            data_type_with_ext = f"{data_type}.zip"

        return "-".join([host, package_date, self.allstudies_str, data_type_with_ext])

    def zip_export_combos(
        self,
        study_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
        datatype_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
        all_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for all study, datatype, and all-data packages, as described in the supplied package
        dictionaries.  This method is a wrapper for the methods that make each set of zip archive types.

        Example Argument Structure:
            study_packages     [host][study_id][package_date][data_type] = file_dict
            datatype_packages  [host][data_type][package_date][study_id] = file_dict
            all_packages       [host][package_date][study_id][data_type] = file_dict

        Example Filename Accessed Inside the above file_dict's:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename Structure:
            study_packages     {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip
            datatype_packages  {hostname}-{datestamp}-allstudies-{data_type}.zip
            all_packages       {hostname}-{datestamp}-allstudies-alldatatypes.zip

        Args:
            study_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe a all-data zip archives, keyed by: host, package_date,
                study_id, and data_type
            datatype_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe study zip archives, keyed by: host, study_id,
                package_date, and data_type
            all_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe datatype zip archives, keyed by: host, data_type,
                package_date, and study_id
        Exceptions:
            None
        Returns:
            None
        """
        self.zip_study_packages(study_packages)
        self.zip_datatype_packages(datatype_packages)
        self.zip_everything_packages(all_packages)

    def zip_study_packages(
        self,
        study_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for study packages, as described in the supplied package dictionary.

        Example Argument Structure:
            study_packages[host][study_id][package_date][data_type] = file_dict

        Example filename accessed inside the file_dict:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename:
            study_packages: {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip

        Args:
            study_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe a all-data zip archives, keyed by: host, package_date,
                study_id, and data_type
        Exceptions:
            None
        Returns:
            None
        """
        # Create study zips (which is all data types of 1 study)
        for host, study_dict in study_packages.items():
            for study_id, package_dict in study_dict.items():
                for package_date, datatype_dict in package_dict.items():
                    study_package_file = os.path.join(
                        self.export_dir,
                        self.compute_study_package_filename(
                            host,
                            package_date,
                            study_id,
                        ),
                    )
                    if not self.package_exists(study_package_file):
                        datatype_files = [d["file"] for d in datatype_dict.values()]
                        self.filepaths_to_zip(datatype_files, study_package_file)

    @classmethod
    def package_exists(cls, filepath: str):
        """Determine if the zip archive package already exists (accounting for staging mode).

        NOTE: This considers staging regardless of self.staging_mode.

        Args:
            filepath (str): Path of the zip archive.
        Exceptions:
            None
        Returns:
            (bool): Whether the zip archive exists (staged or unstaged).
        """
        unstaged_filepath = os.path.splitext(filepath)[0]
        return (
            os.path.exists(filepath)
            or (filepath.endswith(cls.staged_ext) and os.path.exists(unstaged_filepath))
            or (
                not filepath.endswith(cls.staged_ext)
                and os.path.exists(f"{filepath}{cls.staged_ext}")
            )
        )

    def zip_datatype_packages(
        self,
        datatype_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for datatype packages, as described in the supplied package dictionary.

        Example Argument Structure:
            datatype_packages[host][data_type][package_date][study_id] = file_dict

        Example Filename Accessed Inside the above file_dict's:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename Structure:
            datatype_packages: {hostname}-{datestamp}-allstudies-{data_type}.zip

        Args:
            datatype_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe study zip archives, keyed by: host, study_id,
                package_date, and data_type
        Exceptions:
            None
        Returns:
            None
        """
        # Create datatype zips (which is all study data of 1 data type)
        for host, datatype_dict in datatype_packages.items():
            for data_type, package_dict in datatype_dict.items():
                for package_date, study_dict in package_dict.items():
                    datatype_package_file = os.path.join(
                        self.export_dir,
                        self.compute_datatype_package_filename(
                            host,
                            package_date,
                            data_type,
                        ),
                    )
                    if not self.package_exists(datatype_package_file):
                        study_files = [
                            cast(str, d["file"]) for d in study_dict.values()
                        ]
                        self.filepaths_to_zip(study_files, datatype_package_file)

    def zip_everything_packages(
        self,
        all_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for all-data packages, as described in the supplied package dictionary.

        Example Argument Structure:
            all_packages[host][package_date][study_id][data_type] = file_dict

        Example Filename Accessed Inside the above file_dict's:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename Structure:
            all_packages: {hostname}-{datestamp}-allstudies-alldatatypes.zip

        Args:
            all_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe datatype zip archives, keyed by: host, data_type,
                package_date, and study_id
        Exceptions:
            None
        Returns:
            None
        """

        # Create "all" zips (which is all data from all studies [for each host and change-date])
        for host, package_dict in all_packages.items():
            for package_date, study_dict in package_dict.items():
                all_package_file = os.path.join(
                    self.export_dir,
                    self.compute_all_package_filename(
                        host,
                        package_date,
                    ),
                )
                if not self.package_exists(all_package_file):
                    all_files = [
                        cast(str, file_dict["file"])
                        for datatype_dict in study_dict.values()
                        for file_dict in datatype_dict.values()
                    ]
                    self.filepaths_to_zip(all_files, all_package_file)

    def filepaths_to_zip(self, filepaths: List[str], zip_filepath: str):
        """Create a zip archive of the files in filepaths.

        Args:
            filepaths (List[str]): Paths to files to be included in the zip archive.  May be absolute paths, but only
                paths relative to the self.export_dir will be in the archive.
            zip_filepath (str): Output filepath of the zip archive.
        Exceptions:
            TypeError: if the arguments are the wrong type.
        Returns:
            None
        """
        if not isinstance(filepaths, list):
            raise TypeError(
                f"file_paths must be a list, not '{type(filepaths).__name__}'."
            )
        elif not isinstance(zip_filepath, str):
            raise TypeError(
                f"zip_filepath must be a str, not '{type(zip_filepath).__name__}'."
            )

        with zipfile.ZipFile(
            zip_filepath, "w", compression=zipfile.ZIP_DEFLATED
        ) as zipf:
            for file_path in filepaths:
                zipf.write(
                    file_path,
                    arcname=os.path.relpath(
                        file_path, start=self.export_dir
                    ).removesuffix(self.staged_ext),
                )

    def unstage_all_files(self):
        """Remove the ".staged" suffix from all staged files under the self.export_dir.

        Args:
            None
        Exceptions:
            None
        Returns:
            None
        """
        if not self.staging_mode:
            return

        export_dir_obj = Path(self.export_dir)
        for staged_filepath in export_dir_obj.glob(f"*{self.staged_ext}"):
            unstaged_filepath = os.path.splitext(staged_filepath)[0]
            os.replace(staged_filepath, unstaged_filepath)


class ExportParseError(Exception):
    def __init__(self, filename: str):
        super().__init__(f"Unable to parse export filename: '{filename}'.")
