import hashlib
import io
import os
import zipfile
from collections import defaultdict
from itertools import zip_longest
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, TextIO, cast

from django.utils.text import get_valid_filename

from DataRepo.models import Study
from DataRepo.utils.export_base import ExportBase


class ExportsOrganizer(ExportBase):
    """A class defining operations to take an export directory containing previously exported data as generated by
    StudiesExporter and organizes it into zip archives at various granularities (all together, by study, and by data
    type).  It is designed to generate these zip archives by host and export date.

    Class Attributes:
        allstudies_str (str): A string included in the zip archive names indicating that all studies are included in the
            file.
        alldatatypes_str (str): A string included in the zip archive names indicating that all data types are included
            in the file.
    Instance Attributes:
        slugified_study_names (Dict[int, str]): Study ID keys mapped to slugified study names.
        export_dir (str): The path to the existing output directory.
        staging_mode (bool) [False]: Write outputs as .staged files and publish them (and staged files produced by
            StudiesExporter.export()) by renaming them to their final names when processing completes.
    """

    allstudies_str = "allstudies"
    alldatatypes_str = "alldatatypes"

    def __init__(self):
        self.slugified_study_names = self.get_slugified_study_names_dict()
        self.export_dir: str
        self.staging_mode = False

    @classmethod
    def get_slugified_study_names_dict(cls):
        """Returns a dict of slugified study names suitable for inclusion in a dash-delimited filename.

        Args:
            None
        Exceptions:
            None
        Returns:
            (Dict[int, str]): Study ID keys mapped to slugified study names.
        """
        return dict(
            (
                rec.id,
                get_valid_filename(rec.name).replace("-", "_"),
            )
            for rec in Study.objects.all()
        )

    def organize(self, export_dir: str, staging_mode=False):
        """Takes an export directory containing previously exported data as generated by StudiesExporter and organizes
        it into zip archives at various granularities (all together, by study, and by data type).  It is designed to
        generate these zip archives by export date.

        It removes exports that have not changed, thereby keeping only those exported files that differ from the
        previous kept export.  Zip archives are created whenever any 1 export file has changed compared to its previous
        version, and the latest version of every other export file is included in the archive.  I.e. Only unique export
        versions are retained once they have been organized.

        It also leaves the individual files intact (as long as they differ from previous exports).

        This method should be called immediately after StudiesExporter.export().

        The files contained must be named in the following ways:

        As output by StudiesExporter.export():
            Individually               Filename: {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{ext}
        As previously organized by this method:
            All studies and datatypes  Filename: {hostname}-{datestamp}-allstudies-alldatatypes.zip
            All studies by datatype    Filename: {hostname}-{datestamp}-allstudies-{data_type}.zip
            All datatypes by study     Filename: {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip

        Example:
            Exported files prior to organization:
                tracebase-2026.04.17-acute_stress-0035-PeakData.tsv
                tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv
                tracebase-2026.04.17-acute_stress-0035-FCirc.tsv
                tracebase-2026.04.17-acute_stress-0035-mzXML.zip
                tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip  # By study, 2026.04.17
                tracebase-2026.04.17-allstudies-alldatatypes.zip         # All together, 2026.04.17
                tracebase-2026.04.17-allstudies-PeakData.zip             # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-PeakGroups.zip           # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-FCirc.zip                # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-mzXML.zip                # By data type, 2026.04.17
                tracebase-2026.04.24-acute_stress-0035-PeakData.tsv      # Same - will be deleted
                tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv    # Same - will be deleted
                tracebase-2026.04.24-acute_stress-0035-FCirc.tsv         # Differs from the 2026.04.17 version
                tracebase-2026.04.24-acute_stress-0035-mzXML.zip         # Same - will be deleted
            Exported files after organization:
                tracebase-2026.04.17-acute_stress-0035-PeakData.tsv      # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv    # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-FCirc.tsv         # NOT included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-mzXML.zip         # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip
                tracebase-2026.04.17-allstudies-alldatatypes.zip
                tracebase-2026.04.17-allstudies-PeakData.zip
                tracebase-2026.04.17-allstudies-PeakGroups.zip
                tracebase-2026.04.17-allstudies-FCirc.zip
                tracebase-2026.04.17-allstudies-mzXML.zip
                tracebase-2026.04.24-acute_stress-0035-FCirc.tsv         # Only one kept from the latest export
                tracebase-2026.04.24-allstudies-alldatatypes.zip         # New file
                tracebase-2026.04.24-allstudies-PeakData.zip             # New file
                tracebase-2026.04.24-allstudies-PeakGroups.zip           # New file
                tracebase-2026.04.24-allstudies-FCirc.zip                # New file
                tracebase-2026.04.24-allstudies-mzXML.zip                # New file
                tracebase-2026.04.24-acute_stress-0035-alldatatypes.zip  # New file
        Args:
            export_dir (str): The path to the existing output directory.
            staging_mode (bool) [False]: Write outputs as .staged files and publish them (and staged files produced by
                StudiesExporter.export()) by renaming them to their final names when processing completes.
        Exceptions:
            None
        Returns:
            None
        """
        self.export_dir = export_dir
        self.staging_mode = staging_mode
        files = [
            os.path.join(export_dir, f)
            for f in os.listdir(export_dir)
            if os.path.isfile(os.path.join(export_dir, f))
        ]
        exports_by_study = self.organize_exports_by_study_and_datatype(files)

        package_dates_by_host = self.remove_unchanged_exports(exports_by_study)
        print(f"C {package_dates_by_host} {exports_by_study}")

        (
            study_packages,
            datatype_packages,
            all_packages,
        ) = self.assemble_export_packages(package_dates_by_host, exports_by_study)
        print(f"D {study_packages}")
        print(f"E {datatype_packages}")
        print(f"F {all_packages}")

        self.zip_export_combos(study_packages, datatype_packages, all_packages)

        self.unstage_all_files()

    def organize_exports_by_study_and_datatype(self, files):
        """Takes a set of export files currently and previously generated by StudiesExporter.export() (and is allowed to
        include [but ignores] previously generated zip archives of combined exports) and returns a dict containing
        metadata of the export files organized by study then data type.

        It ignores any supplied files that have been previously organized into zip archives (and distinguishes them from
        zip archives generated by StudiesExporter.export()).

        Example:
            exports_by_study = self.organize_exports_by_study_and_datatype(
                [
                    "tracebase-2026.04.17-acute_stress-0035-PeakData.tsv",
                    "tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv",
                    "tracebase-2026.04.17-acute_stress-0035-FCirc.tsv",
                    "tracebase-2026.04.17-acute_stress-0035-mzXML.zip",
                    "tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip",
                    "tracebase-2026.04.17-allstudies-alldatatypes.zip",
                    "tracebase-2026.04.17-allstudies-PeakData.zip",
                    "tracebase-2026.04.17-allstudies-PeakGroups.zip",
                    "tracebase-2026.04.17-allstudies-FCirc.zip",
                    "tracebase-2026.04.17-allstudies-mzXML.zip",
                    "tracebase-2026.04.24-acute_stress-0035-PeakData.tsv",
                    "tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv",
                    "tracebase-2026.04.24-acute_stress-0035-FCirc.tsv",
                    "tracebase-2026.04.24-acute_stress-0035-mzXML.zip",
                ]
            )
            # bystudy = {
            #     "tracebase": {
            #         "0035": {
            #             "PeakData": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-PeakData.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakData",
            #                     "staged": False,
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-PeakData.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakData",
            #                     "staged": False,
            #                 },
            #             ],
            #             "PeakGroups": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakGroups",
            #                     "staged": False,
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakGroups",
            #                     "staged": False,
            #                 },
            #             ],
            #             "FCirc": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-FCirc.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "FCirc",
            #                     "staged": False,
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-FCirc.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "FCirc",
            #                     "staged": False,
            #                 },
            #             ],
            #             "mzXML": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-mzXML.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "mzXML",
            #                     "staged": False,
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-mzXML.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "mzXML",
            #                     "staged": False,
            #                 },
            #             ],
            #         }
            #     }
            # }
        Args:
            files (List[str]): List of filepaths of previously organized and new export files.
        Exceptions:
            None
        Returns:
            study_then_datatype_data (Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]])
        """
        study_names = dict((rec.id, rec.name) for rec in Study.objects.all())
        study_then_datatype_data: Dict[
            str, Dict[str, Dict[str, List[Dict[str, str]]]]
        ] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))

        for file in sorted(files):
            host, date_str, slugged_study_name, study_key, data_type, ext, staged = (
                self.parse_export_filename(file)
            )
            if study_key and data_type != self.alldatatypes_str:
                study_id = int(study_key)  # Removes leading zeroes
                study_then_datatype_data[host][study_key][data_type].append(
                    {
                        "date": date_str,
                        "file": file,
                        "id": study_id,
                        "name": study_names[study_id],
                        "slug": slugged_study_name,
                        "ext": ext,
                        "data_type": data_type,
                        "staged": staged,
                    }
                )

        return study_then_datatype_data

    @classmethod
    def parse_export_filename(cls, filepath: str):
        """Takes a filepath and returns a tuple of the file name components.

        Examples:
            "tracebase-2026.04.17-acute_stress-0035-FCirc.tsv"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "FCirc", ".tsv")

            "tracebase-2026.04.17-acute_stress-0035-mzXML.zip"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "mzXML", ".zip")

            "tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "alldatatypes", ".zip")

            "tracebase-2026.04.17-allstudies-alldatatypes.zip"
            -> ("tracebase", "2026.04.17", "allstudies", None, "alldatatypes", ".zip")

            "tracebase-2026.04.17-allstudies-PeakData.zip"
            -> ("tracebase", "2026.04.17", "allstudies", None, "PeakData", ".zip")
        Args:
            filename (str)
        Exceptions:
            ExportParseError
        Returns:
            host (str): hostname, e.g. "tracebase"
            date_str (str): Date, E.g. "2026.04.17"
            slugged_study_name (str): Study name, as parsed from the file, e.g. "acute_stress".  This can have a special
                value of "allstudies" (as parsed from the file).
            study_id (Optional[str]): A 4-digit study ID with leading zeroes, e.g. "0035".  This will be None in the
                event that the file is a combination of studies.
            data_type (str): Data type, e.g. "PeakData".  This can have a special value of "alldatatypes" (as parsed
                from the file).
            ext (str): File extension (no dot)
        """
        study_id: Optional[str]

        filenameext = os.path.basename(filepath)
        filename: str
        filename, ext = os.path.splitext(filenameext)

        if ext == cls.staged_ext:
            staged = True
            filename, ext = os.path.splitext(filename)
        else:
            staged = False

        fn_components = filename.split("-")
        if len(fn_components) == 4 and (
            fn_components[2] == cls.allstudies_str
            or fn_components[3] == cls.alldatatypes_str
        ):
            study_id = None
            host, date_str, slugged_study_name, data_type = fn_components
        elif len(fn_components) == 5:
            host, date_str, slugged_study_name, study_id, data_type = fn_components
        else:
            raise ExportParseError(filename)

        return (host, date_str, slugged_study_name, study_id, data_type, ext, staged)

    def remove_unchanged_exports(
        self, exports_by_study: Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]]
    ):
        """This compares export files generated on different dates and if they do not differ (other than by date), keeps
        the older one.  It removes the newer file from the file system and from the exports_by_study dict.  It returns
        data structures defining all the files that should go into study and datatype packages by date.
        """
        package_dates_by_host: Dict[str, Set[str]] = defaultdict(set)

        # Go through all the exports and cull any later exports that have not changed compared to previous exports
        for host, study_dict in exports_by_study.items():
            for datatype_dict in study_dict.values():
                for data_type, file_dict_list in datatype_dict.items():

                    # We're going to be culling the list for identical exports (aside from export date).  We will
                    # replace the current list with this new one.
                    new_file_dict_list = []

                    # Sort the file_dict_list by export date.  (NOTE: Technically, file_dict_list is already sorted by
                    # date because the files were sorted and the filename starts with (the host, then) the date, but
                    # we're sorting here because we don't want to assume the list was constructed correctly.)
                    date_sorted_file_dict_list = sorted(
                        file_dict_list, key=lambda d: d["date"]
                    )
                    prev_file_dict = date_sorted_file_dict_list[0]
                    new_file_dict_list.append(prev_file_dict)

                    # The first date is a package because if "differs" from the previous export (no export)
                    package_dates_by_host[host].add(
                        date_sorted_file_dict_list[0]["date"]
                    )

                    for file_dict in date_sorted_file_dict_list[1:]:

                        # Remove newer exports that do not differ from previous exports
                        if not self.files_differ(
                            prev_file_dict["file"], file_dict["file"]
                        ):
                            # Delete the last file and set the last dict's file to the previous
                            os.remove(file_dict["file"])
                            print(f'H REMOVING {file_dict["file"]}')
                        else:
                            prev_file_dict = file_dict
                            package_dates_by_host[host].add(file_dict["date"])
                            new_file_dict_list.append(file_dict)

                    datatype_dict[data_type] = new_file_dict_list

        return package_dates_by_host

    def assemble_export_packages(
        self,
        package_dates_by_host: Dict[str, Set[str]],
        exports_by_study: Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]],
    ):
        """This constructs a plan for each of the zip archive types in the form of 3 dictionaries:

        - all_packages_by_differing_dates - This dictionary specifies all the files to be included in a zip file
          containing all current data up to a given date (for each host).
        - study_packages_by_differing_dates - This dictionary specifies all the files to be included in a zip file
          containing all current data **per study** up to a given date (for each host).
        - datatype_packages_by_differing_dates - This dictionary specifies all the files to be included in a zip file
          containing all current data **per data type** up to a given date (for each host).

        It uses the most recent export at or before each export date in the exports_by_study data structure for each
        file type.  To exclude unchanged exports, see remove_unchanged_exports to modify exports_by_study to exclude
        redundant files.

        Args:
            package_dates_by_host (Dict[str, Set[str]]): A set of package dates (when at least 1 data file changed),
                stored by host key.
            exports_by_study (Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]]): Lists of file meta dictionaries
                describing a study export zip archives, stored by keys: host, study ID, and datatype
        Exceptions:
            None
        Returns:
            all_packages_by_differing_dates (Dict[str, Dict[str, Dict[str, Dict[str, dict]]]]):
                Dictionary of file dictionaries that describe a all-data zip archives, keyed by: host, package_date,
                study_id, and data_type
            study_packages_by_differing_dates (Dict[str, Dict[str, Dict[str, Dict[str, dict]]]]):
                Dictionary of file dictionaries that describe study zip archives, keyed by: host, study_id,
                package_date, and data_type
            datatype_packages_by_differing_dates (Dict[str, Dict[str, Dict[str, Dict[str, dict]]]]):
                Dictionary of file dictionaries that describe datatype zip archives, keyed by: host, data_type,
                package_date, and study_id
        """
        # host, package date, study, data type -> file dict
        all_packages_by_differing_dates: Dict[
            str, Dict[str, Dict[str, Dict[str, dict]]]
        ] = defaultdict(
            lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))
        )

        # host, study, package date, data type -> file dict
        study_packages_by_differing_dates: Dict[
            str, Dict[str, Dict[str, Dict[str, dict]]]
        ] = defaultdict(
            lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))
        )

        # host, data type, package date, study -> file dict
        datatype_packages_by_differing_dates: Dict[
            str, Dict[str, Dict[str, Dict[str, dict]]]
        ] = defaultdict(
            lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))
        )

        # Assemble the file dicts for each package for the identified export dates (the dates where at least 1 thing
        # changed).  Note, the export dates of each file must be on or before each export date.
        print("G1")
        for host, package_dates in package_dates_by_host.items():
            for package_date in sorted(package_dates):
                for study_id, datatype_dict in exports_by_study[host].items():
                    print(f"G4 {study_id} {datatype_dict}")
                    for data_type, file_dict_list in datatype_dict.items():
                        print(f"G5 {data_type} {file_dict_list}")
                        for file_dict in sorted(
                            file_dict_list, key=lambda d: d["date"], reverse=True
                        ):
                            if file_dict["date"] > package_date:
                                print(f'G {file_dict["date"]} > {package_date}')
                                continue
                            else:
                                print(
                                    f"G {host} {package_date} {study_id} {data_type} {file_dict}"
                                )
                                all_packages_by_differing_dates[host][package_date][
                                    study_id
                                ][data_type] = file_dict

                                study_packages_by_differing_dates[host][study_id][
                                    package_date
                                ][data_type] = file_dict

                                datatype_packages_by_differing_dates[host][data_type][
                                    package_date
                                ][study_id] = file_dict

                                # Stop at the latest version BEFORE or equal to the package date
                                break

        return (
            study_packages_by_differing_dates,
            datatype_packages_by_differing_dates,
            all_packages_by_differing_dates,
        )

    @classmethod
    def files_differ(cls, filepath1: str, filepath2: str):
        """This is a wrapper for mzxml_zips_differ and tsv_files_differ, which are called based on the value of zip.  It
        only works for tsv and zip files and ignores commented lines (in order to ignore different export dates in the
        commented header).

        Args:
            filepath1 (str)
            filepath2 (str)
        Exceptions:
            ValueError: When there's a problem with the file extensions.
        Returns:
            (bool): Whether TraceBase export the files differ or not (by anything other than export date)
        """
        filepath1_basename, ext1 = os.path.splitext(filepath1)
        # Account for the "staged" extension
        if ext1 == cls.staged_ext:
            ext1 = os.path.splitext(filepath1_basename)[1]

        filepath2_basename, ext2 = os.path.splitext(filepath2)
        # Account for the "staged" extension
        if ext2 == cls.staged_ext:
            ext2 = os.path.splitext(filepath2_basename)[1]

        if ext1 != ext2:
            raise ValueError(
                "files_differ is only intended to compare files with the same extension. "
                f"'{ext1}' != '{ext2}'."
            )

        if ext1.lower() == ".zip":
            return cls.mzxml_zips_differ(filepath1, filepath2)
        if ext1.lower() != ".tsv":
            raise ValueError(
                f"files_differ supports only zip and tsv files, not '{ext1}'."
            )

        return cls.tsv_files_differ(filepath1, filepath2)

    @classmethod
    def mzxml_zips_differ(cls, filepath1: str, filepath2: str):
        """Determines if 2 mzXML zip export files differ by anything other than export date.  It specifically looks at
        the mzXML files themselves and the single tsv metadata file at the top level of the zip archive.

        Args:
            filepath1 (str)
            filepath2 (str)
        Exceptions:
            NotOneMzxmlMetadataFile
        Returns:
            (bool): Whether the files differ by anything other than export date
        """
        differs = False

        with (
            zipfile.ZipFile(filepath1, "r") as zp,
            zipfile.ZipFile(filepath2, "r") as zn,
        ):
            # This avoids retrieving zip archive metadata files by restricting to matches in the root level directory
            prev_tsv_files = [
                name
                for name in zp.namelist()
                if (name.endswith(".tsv") or name.endswith(f".tsv{cls.staged_ext}"))
                and len(name.split("/")) == 2
            ]
            current_tsv_files = [
                name
                for name in zn.namelist()
                if (name.endswith(".tsv") or name.endswith(f".tsv{cls.staged_ext}"))
                and len(name.split("/")) == 2
            ]

            if len(prev_tsv_files) != 1:
                raise NotOneMzxmlMetadataFile(filepath1, prev_tsv_files)

            if len(current_tsv_files) != 1:
                raise NotOneMzxmlMetadataFile(filepath2, current_tsv_files)

            prev_tsv = prev_tsv_files[0]
            current_tsv = current_tsv_files[0]

            # Access the member as a binary file-like object
            with (
                zp.open(prev_tsv) as prev_binary_file,
                zn.open(current_tsv) as current_binary_file,
            ):
                # Wrap the binary stream to handle text decoding
                with (
                    io.TextIOWrapper(
                        prev_binary_file, encoding="utf-8"
                    ) as prev_file_obj,
                    io.TextIOWrapper(
                        current_binary_file, encoding="utf-8"
                    ) as current_file_obj,
                ):
                    differs = cls.tsv_file_objs_differ(prev_file_obj, current_file_obj)
                    if differs:
                        return differs

        # If the tsvs are the same, also check if the actual mzXML files changed
        prev_mzxml_checksums = cls.get_mzxml_zip_checksums(filepath1)
        next_mzxml_checksums = cls.get_mzxml_zip_checksums(filepath2)

        return prev_mzxml_checksums.items() != next_mzxml_checksums.items()

    @classmethod
    def tsv_files_differ(cls, filepath1: str, filepath2: str):
        """Determines if 2 tsv export files differ by anything other than export date.  It ignores commented lines to
        avoid the different export dates in the commented header.

        Args:
            filepath1 (str)
            filepath2 (str)
        Exceptions:
            None
        Returns:
            (bool): Whether the files differ by anything other than export date
        """
        with open(filepath1, "r") as f1, open(filepath2, "r") as f2:
            return cls.tsv_file_objs_differ(f1, f2)

    @classmethod
    def tsv_file_objs_differ(cls, file1_obj: TextIO, file2_obj: TextIO):
        """Determines if 2 tsv export file objects differ by anything other than export date.  It ignores commented
        lines to avoid the different export dates in the commented header.

        Args:
            file1_obj (TextIO)
            file2_obj (TextIO)
        Exceptions:
            NotOneMzxmlMetadataFile
        Returns:
            (bool): Whether the file objects differ by anything other than export date
        """
        # Create generators that skip comments
        file1_generator = (line for line in file1_obj if not str(line).startswith("#"))
        file2_generator = (line for line in file2_obj if not str(line).startswith("#"))

        # compare line by line; return False immediately if a mismatch is found
        for file1_line, file2_line in zip_longest(file1_generator, file2_generator):
            if file1_line != file2_line:
                return True

        return False

    @classmethod
    def get_mzxml_zip_checksums(cls, zip_path: str):
        """Takes a zip archive filepath and returns a dict of all the mzXML filepaths mapped to their checksums.

        The intended use is to determine of any mzXML files changed inside the archive when compared to another archive.

        Args:
            zip_path (str): The file path of the zip archive
        Exceptions:
            None
        Returns:
            checksums (Dict[str, str])
        """
        checksums: Dict[str, str] = {}
        with zipfile.ZipFile(zip_path, "r") as zip_h:
            # Filter files by extension
            mzxml_files = [
                filepath
                for filepath in zip_h.namelist()
                if (
                    filepath.lower().endswith(".mzxml")
                    # Avoid zip metadata, (that start with "._")
                    and not os.path.basename(filepath).startswith("._")
                )
            ]

            for file_name in mzxml_files:
                # Open file in-memory without extracting to disk
                with zip_h.open(file_name) as f:
                    sha256_hash = hashlib.sha256()
                    # Read in chunks for memory efficiency with large files
                    for byte_block in iter(lambda: f.read(4096), b""):
                        sha256_hash.update(byte_block)
                    checksums[file_name] = sha256_hash.hexdigest()

        return checksums

    def compute_all_package_filename(self, host: str, package_date: str):
        """Given the host name and the package date, returns a zip archive filename representing all data exported on or
        before a given date and host.

        Assumptions:
            1. None of the arguments contain dashes.  The date is assumed to have been formatted with dots and the host
               is assumpd to have had dashes converted to underscores, each of which happens before we get here.
        Args:
            host (str)
            package_date (str)
        Exceptions:
            ValueError: If any argument contains a dash.
        Returns:
            (str): The name of the all export data archive file (for a given host and export date)
        """
        if "-" in host or "-" in package_date:
            raise ValueError(
                f"Arguments may not contain dashes ('{host}', '{package_date}' were supplied)."
            )

        if self.staging_mode:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip{self.staged_ext}"
        else:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip"

        return "-".join(
            [host, package_date, self.allstudies_str, alldatatypes_with_ext]
        )

    def compute_study_package_filename(
        self, host: str, package_date: str, study_key: str
    ):
        """Given the host name, the package date, and a study key (with leading zeroes), returns a zip archive filename
        representing all data exported for a particular study on or before a given date and host.

        Assumptions:
            1. None of the arguments contain dashes.  The date is assumed to have been formatted with dots, the host is
               assumed to have had dashes converted to underscores, and the study key is assumed to have had dashes and
               spaces converted to underscores, all of which happens before we get here.
        Args:
            host (str)
            package_date (str)
            study_key (str): E.g. "0003"
        Exceptions:
            ValueError: If any argument contains a dash.
        Returns:
            (str): The name of the all export data archive file (for a given host and export date)
        """
        if "-" in host or "-" in package_date:
            raise ValueError(
                f"Arguments may not contain dashes ('{host}', '{package_date}' were supplied)."
            )
        study_id = int(study_key)

        if self.staging_mode:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip{self.staged_ext}"
        else:
            alldatatypes_with_ext = f"{self.alldatatypes_str}.zip"

        return "-".join(
            [
                host,
                package_date,
                self.slugified_study_names[study_id],
                alldatatypes_with_ext,
            ]
        )

    def compute_datatype_package_filename(
        self, host: str, package_date: str, data_type: str
    ):
        """Given the host name, the package date, and a study key (with leading zeroes), returns a zip archive filename
        representing all data exported for a particular study on or before a given date and host.

        Assumptions:
            1. None of the arguments contain dashes.  The date is assumed to have been formatted with dots, the host is
               assumed to have had dashes converted to underscores, and the study key is assumed to have had dashes and
               spaces converted to underscores, all of which happens before we get here.
        Args:
            host (str)
            package_date (str)
            study_key (str): E.g. "0003"
        Exceptions:
            ValueError: If any argument contains a dash.
        Returns:
            (str): The name of the all export data archive file (for a given host and export date)
        """
        if "-" in host or "-" in package_date or "-" in data_type:
            raise ValueError(
                "Arguments may not contain dashes "
                f"('{host}', '{package_date}', '{data_type}' were supplied)."
            )

        if self.staging_mode:
            data_type_with_ext = f"{data_type}.zip{self.staged_ext}"
        else:
            data_type_with_ext = f"{data_type}.zip"

        return "-".join([host, package_date, self.allstudies_str, data_type_with_ext])

    def zip_export_combos(
        self,
        study_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
        datatype_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
        all_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for all study, datatype, and all-data packages, as described in the supplied package
        dictionaries.  This method is a wrapper for the methods that make each set of zip archive types.

        Example Argument Structure:
            study_packages     [host][study_id][package_date][data_type] = file_dict
            datatype_packages  [host][data_type][package_date][study_id] = file_dict
            all_packages       [host][package_date][study_id][data_type] = file_dict

        Example Filename Accessed Inside the above file_dict's:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename Structure:
            study_packages     {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip
            datatype_packages  {hostname}-{datestamp}-allstudies-{data_type}.zip
            all_packages       {hostname}-{datestamp}-allstudies-alldatatypes.zip

        Args:
            study_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe a all-data zip archives, keyed by: host, package_date,
                study_id, and data_type
            datatype_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe study zip archives, keyed by: host, study_id,
                package_date, and data_type
            all_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe datatype zip archives, keyed by: host, data_type,
                package_date, and study_id
        Exceptions:
            None
        Returns:
            None
        """
        self.zip_study_packages(study_packages)
        self.zip_datatype_packages(datatype_packages)
        self.zip_everything_packages(all_packages)

    def zip_study_packages(
        self,
        study_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for study packages, as described in the supplied package dictionary.

        Example Argument Structure:
            study_packages[host][study_id][package_date][data_type] = file_dict

        Example filename accessed inside the file_dict:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename:
            study_packages: {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip

        Args:
            study_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe a all-data zip archives, keyed by: host, package_date,
                study_id, and data_type
        Exceptions:
            None
        Returns:
            None
        """
        # Create study zips (which is all data types of 1 study)
        for host, study_dict in study_packages.items():
            print(f"H1 {host} {study_dict}")
            for study_id, package_dict in study_dict.items():
                print(f"H2 {study_id} {package_dict}")
                for package_date, datatype_dict in package_dict.items():
                    study_package_file = os.path.join(
                        self.export_dir,
                        self.compute_study_package_filename(
                            host,
                            package_date,
                            study_id,
                        ),
                    )
                    if not self.package_exists(study_package_file):
                        datatype_files = [d["file"] for d in datatype_dict.values()]
                        print(f"H5 {datatype_files}")
                        self.filepaths_to_zip(datatype_files, study_package_file)

    @classmethod
    def package_exists(cls, filepath: str):
        """Determine if the zip archive package already exists (accounting for staging mode).

        NOTE: This considers staging regardless of self.staging_mode.

        Args:
            filepath (str): Path of the zip archive.
        Exceptions:
            None
        Returns:
            (bool): Whether the zip archive exists (staged or unstaged).
        """
        unstaged_filepath = os.path.splitext(filepath)[0]
        return (
            os.path.exists(filepath)
            or (filepath.endswith(cls.staged_ext) and os.path.exists(unstaged_filepath))
            or (
                not filepath.endswith(cls.staged_ext)
                and os.path.exists(f"{filepath}{cls.staged_ext}")
            )
        )

    def zip_datatype_packages(
        self,
        datatype_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for datatype packages, as described in the supplied package dictionary.

        Example Argument Structure:
            datatype_packages[host][data_type][package_date][study_id] = file_dict

        Example Filename Accessed Inside the above file_dict's:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename Structure:
            datatype_packages: {hostname}-{datestamp}-allstudies-{data_type}.zip

        Args:
            datatype_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe study zip archives, keyed by: host, study_id,
                package_date, and data_type
        Exceptions:
            None
        Returns:
            None
        """
        # Create datatype zips (which is all study data of 1 data type)
        for host, datatype_dict in datatype_packages.items():
            print(f"K0 {host} {datatype_dict}")
            for data_type, package_dict in datatype_dict.items():
                print(f"K1 {data_type} {package_dict}")
                for package_date, study_dict in package_dict.items():
                    datatype_package_file = os.path.join(
                        self.export_dir,
                        self.compute_datatype_package_filename(
                            host,
                            package_date,
                            data_type,
                        ),
                    )
                    if not self.package_exists(datatype_package_file):
                        study_files = [
                            cast(str, d["file"]) for d in study_dict.values()
                        ]
                        print(f"K4 {study_files}")
                        self.filepaths_to_zip(study_files, datatype_package_file)

    def zip_everything_packages(
        self,
        all_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        """Creates zip archives for all-data packages, as described in the supplied package dictionary.

        Example Argument Structure:
            all_packages[host][package_date][study_id][data_type] = file_dict

        Example Filename Accessed Inside the above file_dict's:
            {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        Example Zip Archive Filename Structure:
            all_packages: {hostname}-{datestamp}-allstudies-alldatatypes.zip

        Args:
            all_packages (Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]]):
                Dictionary of file dictionaries that describe datatype zip archives, keyed by: host, data_type,
                package_date, and study_id
        Exceptions:
            None
        Returns:
            None
        """

        # Create "all" zips (which is all data from all studies [for each host and change-date])
        for host, package_dict in all_packages.items():
            for package_date, study_dict in package_dict.items():
                all_package_file = os.path.join(
                    self.export_dir,
                    self.compute_all_package_filename(
                        host,
                        package_date,
                    ),
                )
                if not self.package_exists(all_package_file):
                    all_files = [
                        cast(str, file_dict["file"])
                        for datatype_dict in study_dict.values()
                        for file_dict in datatype_dict.values()
                    ]
                    self.filepaths_to_zip(all_files, all_package_file)

    def filepaths_to_zip(self, filepaths: List[str], zip_filepath: str):
        """Create a zip archive of the files in filepaths.

        Args:
            filepaths (List[str]): Paths to files to be included in the zip archive.  May be absolute paths, but only
                paths relative to the self.export_dir will be in the archive.
            zip_filepath (str): Output filepath of the zip archive.
        Exceptions:
            TypeError: if the arguments are the wrong type.
        Returns:
            None
        """
        if not isinstance(filepaths, list):
            raise TypeError(
                f"file_paths must be a list, not '{type(filepaths).__name__}'."
            )
        elif not isinstance(zip_filepath, str):
            raise TypeError(
                f"zip_filepath must be a str, not '{type(zip_filepath).__name__}'."
            )

        with zipfile.ZipFile(
            zip_filepath, "w", compression=zipfile.ZIP_DEFLATED
        ) as zipf:
            for file_path in filepaths:
                zipf.write(
                    file_path,
                    arcname=os.path.relpath(
                        file_path, start=self.export_dir
                    ).removesuffix(self.staged_ext),
                )

    def unstage_all_files(self):
        """Remove the ".staged" suffix from all staged files under the self.export_dir.

        Args:
            None
        Exceptions:
            None
        Returns:
            None
        """
        if not self.staging_mode:
            return

        export_dir_obj = Path(self.export_dir)
        for staged_filepath in export_dir_obj.glob(f"*{self.staged_ext}"):
            unstaged_filepath = os.path.splitext(staged_filepath)[0]
            os.replace(staged_filepath, unstaged_filepath)


class ExportParseError(Exception):
    def __init__(self, filename: str):
        super().__init__(f"Unable to parse export filename: '{filename}'.")


class NotOneMzxmlMetadataFile(Exception):
    def __init__(self, zip_archive_file: str, metadata_files: List[str]):
        message = (
            f"Zip archive '{zip_archive_file}' was expected to have 1 TSV file (for metadata), but was found to have "
            f"{len(metadata_files)}"
        )
        message += "." if len(metadata_files) == 0 else f": {metadata_files}."
        super().__init__(message)
