import hashlib
import io
import os
import zipfile
from collections import defaultdict
from itertools import zip_longest
from typing import Any, Dict, List, Optional, Set, cast

from django.utils.text import get_valid_filename

from DataRepo.models import Study


class ExportsOrganizer:

    allstudies_str = "allstudies"
    alldatatypes_str = "alldatatypes"

    def __init__(self):
        self.slugified_study_names = self.get_slugified_study_names_dict()

    @classmethod
    def get_slugified_study_names_dict(cls):
        return dict(
            (
                rec.id,
                get_valid_filename(rec.name).replace("-", "_"),
            )
            for rec in Study.objects.all()
        )

    def organize(self, export_dir: str):
        """Takes an export directory containing previously organized^ exports and one unorganized^ export and it
        organizes^ that 1 latest unorganized^ export, as generated by StudiesExporter and output to the export_dir,
        which accumulates exports.  This method should be called immediately after StudiesExporter.export().

        The files contained must be named in the following ways:

        As output by StudiesExporter.export():
            Individually               Filename: {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{ext}
        As previously organized by this method:
            All studies and datatypes  Filename: {hostname}-{datestamp}-allstudies-alldatatypes.zip
            All studies by datatype    Filename: {hostname}-{datestamp}-allstudies-{data_type}.zip
            All datatypes by study     Filename: {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip

        ^ "organize", as used here, as a term, means that it goes through all export files directly in the export_dir
          (i.e. subdirectories are ignored) and determines the last/latest exported versions (by datestamp), and zips
          them in 3 ways:
            All together.
            By study.
            By data type.

        It also leaves the latest individual files and deletes those that only differ from the previous version by
        export date.

        The purpose of doing it this way is so that new exports are not retained if they only differ from previous
        exports by export date.  I.e. An exported file will be deleted if it only differs from the previous export by
        export date.  The guiding strategy is that only unique export versions are retained once they have been
        organized.

        Another aspect of this organization is that it zips all files from the latest export~ together, all files of a
        single datatype together, and all files of a single study together.  This is a convenience feature for users so
        that they can select the type and amount of data they want in a single download click on the downloads page
        where these exports will be served.

        ~ "Latest export" means the last study/datatype that differs from the previous export.  That may not be the
          latest date in any one case.  E.g. If study "A" had no change to its FCirc data in the latest export, that
          'Study A FCirc' file is deleted and the file used for zipping in various combinations falls back to the
          previous version exported the week prior.

        If any individual file from the last export has changed, all combination zip files it is included in will be re-
        zipped with a new date (date is a stand-in for version).

        Example:
            Exported files prior to organization:
                tracebase-2026.04.17-acute_stress-0035-PeakData.tsv
                tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv
                tracebase-2026.04.17-acute_stress-0035-FCirc.tsv
                tracebase-2026.04.17-acute_stress-0035-mzXMLs.zip
                tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip  # By study, 2026.04.17
                tracebase-2026.04.17-allstudies-alldatatypes.zip         # All together, 2026.04.17
                tracebase-2026.04.17-allstudies-PeakData.zip             # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-PeakGroups.zip           # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-FCirc.zip                # By data type, 2026.04.17
                tracebase-2026.04.17-allstudies-mzXMLs.zip               # By data type, 2026.04.17
                tracebase-2026.04.24-acute_stress-0035-PeakData.tsv      # Same - will be deleted
                tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv    # Same - will be deleted
                tracebase-2026.04.24-acute_stress-0035-FCirc.tsv         # Differs from the 2026.04.17 version
                tracebase-2026.04.24-acute_stress-0035-mzXMLs.zip        # Same - will be deleted
            Exported files after organization:
                tracebase-2026.04.17-acute_stress-0035-PeakData.tsv      # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv    # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-FCirc.tsv         # NOT included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-mzXMLs.zip        # Included in the 2026.04.24 zips
                tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip
                tracebase-2026.04.17-allstudies-alldatatypes.zip
                tracebase-2026.04.17-allstudies-PeakData.zip
                tracebase-2026.04.17-allstudies-PeakGroups.zip
                tracebase-2026.04.17-allstudies-FCirc.zip
                tracebase-2026.04.17-allstudies-mzXMLs.zip
                tracebase-2026.04.24-acute_stress-0035-FCirc.tsv         # Only one kept from the latest export
                tracebase-2026.04.24-allstudies-alldatatypes.zip         # New file
                tracebase-2026.04.24-allstudies-PeakData.zip             # New file
                tracebase-2026.04.24-allstudies-PeakGroups.zip           # New file
                tracebase-2026.04.24-allstudies-FCirc.zip                # New file
                tracebase-2026.04.24-allstudies-mzXMLs.zip               # New file
                tracebase-2026.04.24-acute_stress-0035-alldatatypes.zip  # New file
        Args:
            export_dir: str
        Exceptions:
            None
        Returns:
            None
        """
        files = [f for f in os.listdir(export_dir) if os.path.isfile(f)]
        (
            exports_by_study,
            exports_by_datatype,  # TODO: I might not need this
            # TODO: I may not need these - I can just check if the file exists.  Check.
            # existing_study_packages,
            # existing_datatype_packages,
        ) = self.organize_exports_by_study_and_datatype(files)

        package_dates_by_host = self.remove_unchanged_exports(exports_by_study)

        (
            study_packages,
            datatype_packages,
            all_packages,
        ) = self.assemble_export_packages(package_dates_by_host, exports_by_study)

        self.zip_export_combos(study_packages, datatype_packages, all_packages)

    def organize_exports_by_study_and_datatype(self, files):
        """Takes a set of export files that includes previously organized^ exports and one unorganized^ series of export
        files (e.g. the files recently generated by StudiesExporter.export()) and it returns 2 dicts containing metadata
        of those files organized by study then data type and by data type then study.

        Example:
            bystudy, bydatatype = self.organize_exports_by_study_and_datatype(
                [
                    "tracebase-2026.04.17-acute_stress-0035-PeakData.tsv",
                    "tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv",
                    "tracebase-2026.04.17-acute_stress-0035-FCirc.tsv",
                    "tracebase-2026.04.17-acute_stress-0035-mzXMLs.zip",
                    "tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip",
                    "tracebase-2026.04.17-allstudies-alldatatypes.zip",
                    "tracebase-2026.04.17-allstudies-PeakData.zip",
                    "tracebase-2026.04.17-allstudies-PeakGroups.zip",
                    "tracebase-2026.04.17-allstudies-FCirc.zip",
                    "tracebase-2026.04.17-allstudies-mzXMLs.zip",
                    "tracebase-2026.04.24-acute_stress-0035-PeakData.tsv",
                    "tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv",
                    "tracebase-2026.04.24-acute_stress-0035-FCirc.tsv",
                    "tracebase-2026.04.24-acute_stress-0035-mzXMLs.zip",
                ]
            )
            # bystudy = {
            #     "tracebase": {
            #         "0035": {
            #             "PeakData": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-PeakData.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakData",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-PeakData.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakData",
            #                 },
            #             ],
            #             "PeakGroups": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakGroups",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakGroups",
            #                 },
            #             ],
            #             "FCirc": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-FCirc.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "FCirc",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-FCirc.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "FCirc",
            #                 },
            #             ],
            #             "mzXMLs": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-mzXMLs.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "mzXMLs",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-mzXMLs.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "mzXMLs",
            #                 },
            #             ],
            #         }
            #     }
            # }
            # bydatatype = {
            #     "tracebase": {
            #         "PeakData": {
            #             "0035": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-PeakData.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakData",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-PeakData.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakData",
            #                 },
            #             ],
            #         },
            #         "PeakGroups": {
            #             "0035": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-PeakGroups.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakGroups",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-PeakGroups.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "PeakGroups",
            #                 },
            #             ],
            #         },
            #         "FCirc": {
            #             "0035": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-FCirc.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "FCirc",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-FCirc.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "FCirc",
            #                 },
            #             ],
            #         },
            #         "mzXMLs": {
            #             "0035": [
            #                 {
            #                     "date": "2026.04.17",
            #                     "file": "tracebase-2026.04.17-acute_stress-0035-mzXMLs.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "mzXMLs",
            #                 },
            #                 {
            #                     "date": "2026.04.24",
            #                     "file": "tracebase-2026.04.24-acute_stress-0035-mzXMLs.tsv",
            #                     "id": 35,
            #                     "name": "Acute Stress",  # From DB
            #                     "slug": "acute_stress",
            #                     "ext": "tsv",
            #                     "data_type": "mzXMLs",
            #                 },
            #             ],
            #         }
            #     }
            # }
        Args:
            files (List[str]): List of filepaths of previously organized and new export files.
        Exceptions:
            None
        Returns:
            study_then_datatype_data (Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]])
            datatype_then_study_data (Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]])
            packaged_exports_by_study (Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]])
            packaged_exports_by_datatype (Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]])
        """
        study_names = dict((rec.id, rec.name) for rec in Study.objects.all())
        study_then_datatype_data: Dict[
            str, Dict[str, Dict[str, List[Dict[str, str]]]]
        ] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
        datatype_then_study_data: Dict[
            str, Dict[str, Dict[str, List[Dict[str, str]]]]
        ] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
        # packaged_exports_by_study: Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]] = defaultdict(
        #     lambda: defaultdict(lambda: defaultdict(list))
        # )
        # packaged_exports_by_datatype: Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]] = defaultdict(
        #     lambda: defaultdict(lambda: defaultdict(list))
        # )
        for file in sorted(files):
            host, date_str, slugged_study_name, study_id, data_type, ext = (
                self.parse_export_filename(file)
            )
            if study_id and data_type != self.alldatatypes_str:
                study_then_datatype_data[host][study_id][data_type].append(
                    {
                        "date": date_str,
                        "file": file,
                        "id": str(int(study_id)),  # Removes leading zeroes
                        "name": study_names[study_id],
                        "slug": slugged_study_name,
                        "ext": ext,
                        "data_type": data_type,
                    }
                )
                datatype_then_study_data[host][data_type][study_id].append(
                    {
                        "date": date_str,
                        "file": file,
                        "id": str(int(study_id)),
                        "name": study_names[study_id],
                        "slug": slugged_study_name,
                        "ext": ext,
                        "data_type": data_type,
                    }
                )
            # else:
            #     packaged_exports_by_study[host][slugged_study_name][data_type].append(
            #         {
            #             "date": date_str,
            #             "file": file,
            #             "id": str(int(study_id)) if study_id else None,
            #             "name": study_names[study_id],
            #             "slug": slugged_study_name,
            #             "ext": ext,
            #             "data_type": data_type,
            #         }
            #     )
            #     packaged_exports_by_datatype[host][data_type][slugged_study_name].append(
            #         {
            #             "date": date_str,
            #             "file": file,
            #             "id": str(int(study_id)) if study_id else None,
            #             "name": study_names[study_id],
            #             "slug": slugged_study_name,
            #             "ext": ext,
            #             "data_type": data_type,
            #         }
            #     )

        return (
            study_then_datatype_data,
            datatype_then_study_data,
            # packaged_exports_by_study,
            # packaged_exports_by_datatype,
        )

    def parse_export_filename(self, filepath: str):
        """Takes a filepath and returns a tuple of the file name components.

        Returns (host, date_str, slugged_study_name, study_id, data_type)

        Examples:
            "tracebase-2026.04.17-acute_stress-0035-mzXMLs.zip"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "mzXMLs")

            "tracebase-2026.04.17-acute_stress-0035-alldatatypes.zip"
            -> ("tracebase", "2026.04.17", "acute_stress", "0035", "alldatatypes")

            "tracebase-2026.04.17-allstudies-alldatatypes.zip"
            -> ("tracebase", "2026.04.17", "allstudies", None, "alldatatypes")

            "tracebase-2026.04.17-allstudies-PeakData.zip"
            -> ("tracebase", "2026.04.17", "allstudies", None, "PeakData")
        Args:
            filename (str)
        Exceptions:
            ExportParseError
        Returns:
            host (str): hostname, e.g. "tracebase"
            date_str (str): Date, E.g. "2026.04.17"
            slugged_study_name (str): Study name, as parsed from the file, e.g. "acute_stress".  This can have a special
                value of "allstudies" (as parsed from the file).
            study_id (Optional[str]): A 4-digit study ID with leading zeroes, e.g. "0035".  This will be None in the
                event that the file is a combination of studies.
            data_type (str): Data type, e.g. "PeakData".  This can have a special value of "alldatatypes" (as parsed
                from the file).
            ext (str): File extension (no dot)
        """
        study_id: Optional[str]

        filenameext = os.path.basename(filepath)
        filename: str
        filename, ext = os.path.splitext(filenameext)

        fn_components = filename.split("-")
        if len(fn_components) == 4 and (
            fn_components[2] == self.allstudies_str
            or fn_components[3] == self.alldatatypes_str
        ):
            study_id = None
            host, date_str, slugged_study_name, data_type = fn_components
        elif len(fn_components) == 5:
            host, date_str, slugged_study_name, study_id, data_type = fn_components
        else:
            raise ExportParseError(f"Unable to parse export file: '{filename}'.")

        return (host, date_str, slugged_study_name, study_id, data_type, ext)

    def remove_unchanged_exports(
        self, exports_by_study: Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]]
    ):
        """This compares export files generated on different dates and if they do not differ (other than by date), keeps
        the older one.  It removes the newer file from the file system and from the by_study_first dict.  It returns
        data structures defining all the files that should go into study and datatype packages by date.
        """
        package_dates_by_host: Dict[str, Set[str]] = defaultdict(set)

        # Go through all the exports and cull any later exports that have not changed compared to previous exports
        for host, study_dict in exports_by_study.items():
            for datatype_dict in study_dict.values():
                for data_type, file_dict_list in datatype_dict.items():

                    # We're going to be culling the list for identical exports (aside from export date).  We will
                    # replace the current list with this new one.
                    new_file_dict_list = []

                    # Sort the file_dict_list by export date.  (NOTE: Technoically, file_dict_list is already sorted by
                    # date because the files were sorted and the filename starts with (the host, then) the date, but
                    # we're soring here because we don't want to assume the list was constructed correctly.)
                    date_sorted_file_dict_list = sorted(
                        file_dict_list, key=lambda d: d["date"]
                    )
                    prev_file_dict = date_sorted_file_dict_list[0]

                    # The first date is a package because if "differs" from the previous export (no export)
                    package_dates_by_host[host].add(
                        date_sorted_file_dict_list[0]["date"]
                    )

                    for file_dict in date_sorted_file_dict_list[1:]:

                        # Remove newer exports that do not differ from previous exports
                        if not self.files_differ(
                            prev_file_dict, file_dict, zip=file_dict["ext"] == "zip"
                        ):
                            # Delete the last file and set the last dict's file to the previous
                            os.remove(file_dict["file"])
                        else:
                            prev_file_dict = file_dict
                            package_dates_by_host[host].add(file_dict["date"])
                            new_file_dict_list.append(file_dict)

                    datatype_dict[data_type] = new_file_dict_list

        return package_dates_by_host

    def assemble_export_packages(
        self,
        package_dates_by_host,
        exports_by_study: Dict[str, Dict[str, Dict[str, List[Dict[str, str]]]]],
    ):
        # host, package date, study, data type -> file dict
        all_packages_by_differing_dates: Dict[
            str, Dict[str, Dict[str, Dict[str, dict]]]
        ] = defaultdict(
            lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))
        )

        # host, study, package date, data type -> file dict
        study_packages_by_differing_dates: Dict[
            str, Dict[str, Dict[str, Dict[str, dict]]]
        ] = defaultdict(
            lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))
        )

        # host, data type, package date, study -> file dict
        datatype_packages_by_differing_dates: Dict[
            str, Dict[str, Dict[str, Dict[str, dict]]]
        ] = defaultdict(
            lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))
        )

        # Assemble the file dicts for each package for the identified export dates (the dates where at least 1 thing
        # changed).  Note, the export dates of each file must be on or before each export date.
        for host, package_dates in package_dates_by_host.items():
            for package_date in package_dates:
                for study_id, datatype_dict in exports_by_study[host].items():
                    for data_type, file_dict_list in datatype_dict.items():
                        for file_dict in sorted(
                            file_dict_list, key=lambda d: d["date"], reverse=True
                        ):
                            if file_dict["date"] > package_date:
                                continue
                            else:
                                all_packages_by_differing_dates[host][package_date][
                                    study_id
                                ][data_type] = file_dict

                                study_packages_by_differing_dates[host][study_id][
                                    package_date
                                ][data_type] = file_dict

                                datatype_packages_by_differing_dates[host][data_type][
                                    package_date
                                ][study_id] = file_dict

                                # Stop at the latest version BEFORE or equal to the package date
                                break

        return (
            study_packages_by_differing_dates,
            datatype_packages_by_differing_dates,
            all_packages_by_differing_dates,
        )

    def files_differ(self, prev_file_dict, current_file_dict, zip=False):
        if zip:
            return self.mzxml_zips_differ(prev_file_dict, current_file_dict)
        return self.tsv_files_differ(prev_file_dict, current_file_dict)

    def mzxml_zips_differ(self, prev_file_dict, current_file_dict):
        """Calls self.tsv_file_objs_differ on the TSV files contained in the mzXML zip files."""
        differs = False

        with (
            zipfile.ZipFile(prev_file_dict["file"], "r") as zp,
            zipfile.ZipFile(current_file_dict["file"], "r") as zn,
        ):
            prev_tsv_files = [name for name in zp.namelist() if name.endswith(".tsv")]
            current_tsv_files = [
                name for name in zn.namelist() if name.endswith(".tsv")
            ]

            if len(prev_tsv_files) != 1:
                raise NotOneMzxmlMetadataFile(prev_file_dict["file"], prev_tsv_files)

            if len(current_tsv_files) != 1:
                raise NotOneMzxmlMetadataFile(
                    current_file_dict["file"], current_tsv_files
                )

            prev_tsv = prev_tsv_files[0]
            current_tsv = current_tsv_files[0]

            # Access the member as a binary file-like object
            with (
                zp.open(prev_tsv) as prev_binary_file,
                zn.open(current_tsv) as current_binary_file,
            ):
                # Wrap the binary stream to handle text decoding
                with (
                    io.TextIOWrapper(
                        prev_binary_file, encoding="utf-8"
                    ) as prev_file_obj,
                    io.TextIOWrapper(
                        current_binary_file, encoding="utf-8"
                    ) as current_file_obj,
                ):
                    differs = self.tsv_file_objs_differ(prev_file_obj, current_file_obj)
                    if differs:
                        return differs

        # If the tsvs are the same, also check if the actual mzXML files changed
        prev_mzxml_checksums = self.get_mzxml_zip_checksums(prev_file_dict["file"])
        next_mzxml_checksums = self.get_mzxml_zip_checksums(current_file_dict["file"])

        return prev_mzxml_checksums.items() != next_mzxml_checksums.items()

    def tsv_files_differ(self, prev_file_dict, last_file_dict):
        with (
            open(prev_file_dict["file"], "r") as f1,
            open(last_file_dict["file"], "r") as f2,
        ):
            return self.tsv_file_objs_differ(f1, f2)

    def tsv_file_objs_differ(self, prev_file_obj, next_file_obj):

        # Create generators that skip comments
        prev_file_generator = (
            line for line in prev_file_obj if not str(line).startswith("#")
        )
        next_file_generator = (
            line for line in next_file_obj if not str(line).startswith("#")
        )

        # compare line by line; return False immediately if a mismatch is found
        for prev_file_line, next_file_line in zip_longest(
            prev_file_generator, next_file_generator
        ):
            if prev_file_line != next_file_line:
                return True

        return False

    def get_mzxml_zip_checksums(self, zip_path):
        checksums = {}
        with zipfile.ZipFile(zip_path, "r") as z:
            # Filter files by extension
            mzxml_files = [f for f in z.namelist() if f.lower().endswith(".mzxml")]

            for file_name in mzxml_files:
                # Open file in-memory without extracting to disk
                with z.open(file_name) as f:
                    sha256_hash = hashlib.sha256()
                    # Read in chunks for memory efficiency with large files
                    for byte_block in iter(lambda: f.read(4096), b""):
                        sha256_hash.update(byte_block)
                    checksums[file_name] = sha256_hash.hexdigest()

        return checksums

    def compute_all_package_filename(self, host: str, package_date: str):
        return "-".join(
            [host, package_date, self.allstudies_str, f"{self.alldatatypes_str}.zip"]
        )

    def compute_study_package_filename(
        self, host: str, package_date: str, study_id: str
    ):
        return "-".join(
            [
                host,
                package_date,
                self.slugified_study_names[study_id],
                f"{self.alldatatypes_str}.zip",
            ]
        )

    def compute_datatype_package_filename(
        self, host: str, package_date: str, data_type: str
    ):
        return "-".join([host, package_date, self.allstudies_str, f"{data_type}.zip"])

    def zip_export_combos(
        self,
        study_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
        datatype_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
        all_packages: Dict[str, Dict[str, Dict[str, Dict[str, Dict[str, Any]]]]],
    ):
        # EXAMPLE: study_packages[host][study_id][package_date][data_type] = file_dict
        # EXAMPLE: datatype_packages[host][data_type][package_date][study_id] = file_dict
        # EXAMPLE: all_packages[host][package_date][study_id][data_type] = file_dict

        # Zip everything
        # Orig Filename: {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.{extension}

        # All studies and datatypes  Filename: {hostname}-{datestamp}-allstudies-alldatatypes.zip
        # All studies by datatype    Filename: {hostname}-{datestamp}-allstudies-{data_type}.zip
        # All datatypes by study     Filename: {hostname}-{datestamp}-{study_name}-{study_id}-alldatatypes.zip
        # Individually               Filename: {hostname}-{datestamp}-{study_name}-{study_id}-{data_type}.zip

        # Create study zips (which is all data types of 1 study)
        for host, study_dict in study_packages.items():
            for study_id, package_dict in study_dict.items():
                for package_date, datatype_dict in package_dict.items():
                    study_package_file = self.compute_study_package_filename(
                        host,
                        package_date,
                        study_id,
                    )
                    if not os.path.exists(study_package_file):
                        datatype_files = [d["file"] for d in datatype_dict.values()]
                        self.filepaths_to_zip(datatype_files, study_package_file)

        # Create datatype zips (which is all study data of 1 data type)
        for host, datatype_dict in datatype_packages.items():
            for data_type, package_dict in datatype_dict.items():
                for package_date, study_dict in package_dict.items():
                    datatype_package_file = self.compute_datatype_package_filename(
                        host,
                        package_date,
                        data_type,
                    )
                    if not os.path.exists(datatype_package_file):
                        study_files = [
                            cast(str, d["file"]) for d in study_dict.values()
                        ]
                        self.filepaths_to_zip(study_files, datatype_package_file)

        # Create "all" zips (which is all data from all studies [for each host and change-date])
        for host, package_dict in all_packages.items():
            for package_date, study_dict in package_dict.items():
                all_package_file = self.compute_all_package_filename(
                    host,
                    package_date,
                )
                if not os.path.exists(all_package_file):
                    all_files = [
                        cast(str, file_dict["file"])
                        for datatype_dict in study_dict.values()
                        for file_dict in datatype_dict.values()
                    ]
                    self.filepaths_to_zip(all_files, all_package_file)

    def filepaths_to_zip(self, file_paths: List[str], zip_filepath: str):
        common_base = os.path.commonpath(file_paths)
        with zipfile.ZipFile(
            zip_filepath, "w", compression=zipfile.ZIP_DEFLATED
        ) as zipf:
            for file_path in file_paths:
                # Calculate the path relative to the common base
                arcname = os.path.relpath(file_path, start=common_base)
                # Use arcname to avoid storing the full absolute path in the zip
                zipf.write(file_path, arcname=arcname)


class ExportParseError(Exception):
    pass


class NotOneMzxmlMetadataFile(Exception):
    def __init__(self, zip_archive_file: str, metadata_files: List[str]):
        message = (
            f"Zip archive '{zip_archive_file}' was expected to have 1 TSV file (for metadata), but was found to have "
            f"{len(metadata_files)}"
        )
        message += "." if len(metadata_files) == 0 else f": {metadata_files}."
        super().__init__(message)
